/**
 * Coastal Key Mobile App — Systems & Diagnostics
 * Fleet health monitoring, auto-repair, event logging, notifications
 */

export function renderSystems() {
  return `
    <div class="flex justify-between items-center mb-lg" style="display:flex;justify-content:space-between;align-items:center;margin-bottom:var(--space-lg);">
      <div>
        <h2 style="font-size:1.35rem;">Systems</h2>
        <p class="text-sm text-dim" style="margin-top:4px;">Fleet diagnostics & monitoring</p>
      </div>
      <button class="btn btn-execute" style="padding:8px 16px;font-size:0.7rem;">Fleet Scan</button>
    </div>

    <!-- System Health Overview -->
    <div class="card-hero mb-lg" style="padding:var(--space-xl);">
      <div style="text-align:center;">
        <div class="gauge-ring" style="--gauge-value:98.7%;width:100px;height:100px;margin:0 auto;">
          <span class="gauge-label" style="font-size:1.1rem;">98.7%</span>
        </div>
        <div style="margin-top:var(--space-md);font-size:0.85rem;font-weight:600;color:#fff;">System Health</div>
        <div style="font-size:0.72rem;color:var(--ck-green);margin-top:4px;">All Systems Operational</div>
      </div>
    </div>

    <!-- Fleet Grid -->
    <div class="section-header">
      <span class="section-title">Division Status</span>
      <button class="section-action">Full Fleet View</button>
    </div>

    ${renderDivisionRow('EXC', 'Executive', 20, 18, 2, 0, '#6366f1')}
    ${renderDivisionRow('SEN', 'Sentinel Sales', 40, 38, 1, 1, '#ef4444')}
    ${renderDivisionRow('OPS', 'Operations', 45, 43, 2, 0, '#f59e0b')}
    ${renderDivisionRow('INT', 'Intelligence', 30, 30, 0, 0, '#10b981')}
    ${renderDivisionRow('MKT', 'Marketing', 40, 39, 1, 0, '#8b5cf6')}
    ${renderDivisionRow('FIN', 'Finance', 25, 25, 0, 0, '#06b6d4')}
    ${renderDivisionRow('VEN', 'Vendor Mgmt', 25, 24, 1, 0, '#f97316')}
    ${renderDivisionRow('TEC', 'Technology', 25, 25, 0, 0, '#64748b')}
    ${renderDivisionRow('WEB', 'Website Dev', 40, 38, 2, 0, '#0ea5e9')}

    <div class="divider"></div>

    <!-- Intelligence Officers -->
    <div class="section-header">
      <span class="section-title">Intelligence Officers</span>
      <button class="section-action">50 Active</button>
    </div>
    <div style="display:grid;grid-template-columns:repeat(5,1fr);gap:var(--space-sm);margin-bottom:var(--space-lg);">
      ${renderSquadBadge('ALPHA', 'Infra', 10, '#ef4444')}
      ${renderSquadBadge('BRAVO', 'Data', 10, '#f59e0b')}
      ${renderSquadBadge('CHARLIE', 'Security', 10, '#10b981')}
      ${renderSquadBadge('DELTA', 'Revenue', 10, '#3b82f6')}
      ${renderSquadBadge('ECHO', 'Perf', 10, '#8b5cf6')}
    </div>

    <!-- Email Agents -->
    <div class="section-header">
      <span class="section-title">Email AI Agents</span>
      <button class="section-action">20 Active</button>
    </div>
    <div style="display:grid;grid-template-columns:repeat(4,1fr);gap:var(--space-sm);margin-bottom:var(--space-lg);">
      ${renderSquadBadge('INTAKE', 'Classify', 5, '#06b6d4')}
      ${renderSquadBadge('COMPOSE', 'Draft', 5, '#a78bfa')}
      ${renderSquadBadge('NURTURE', 'Drip', 5, '#34d399')}
      ${renderSquadBadge('MONITOR', 'Track', 5, '#f97316')}
    </div>

    <div class="divider"></div>

    <!-- Auto-Repair Log -->
    <div class="section-header">
      <span class="section-title">Recent Events</span>
      <button class="section-action">Full Log</button>
    </div>

    ${renderEventLog('12:45 PM', 'Fleet scan completed — 360/360 units responsive', 'green')}
    ${renderEventLog('11:30 AM', 'SEN-014 auto-repair triggered — rate limit adjustment', 'amber')}
    ${renderEventLog('10:15 AM', 'CHARLIE squad security scan — no anomalies detected', 'green')}
    ${renderEventLog('9:00 AM', 'Daily market brief generated by INT division', 'blue')}
    ${renderEventLog('8:00 AM', 'System startup — all KV namespaces healthy', 'green')}
    ${renderEventLog('Yesterday', 'BRAVO squad data integrity check — 38/38 tables verified', 'green')}

    <div class="divider"></div>

    <!-- Diagnostics Actions -->
    <div class="section-header">
      <span class="section-title">Diagnostics</span>
    </div>
    <div style="display:grid;grid-template-columns:1fr 1fr;gap:var(--space-sm);">
      <button class="btn btn-secondary" style="font-size:0.75rem;padding:12px;">Deep Health Check</button>
      <button class="btn btn-secondary" style="font-size:0.75rem;padding:12px;">KV Namespace Audit</button>
      <button class="btn btn-ghost" style="font-size:0.75rem;padding:12px;">Airtable Sync Status</button>
      <button class="btn btn-ghost" style="font-size:0.75rem;padding:12px;">API Latency Report</button>
    </div>

    <!-- Governance Footer -->
    <div class="divider"></div>
    <div style="text-align:center;padding:var(--space-sm) 0;">
      <div style="font-size:0.6rem;color:var(--ck-gold-dim);letter-spacing:0.08em;">Sovereign Governance Compendium v1.0 &middot; All agents compliant</div>
    </div>
  `;
}

function renderDivisionRow(code, name, total, active, standby, error, color) {
  const pct = Math.round((active / total) * 100);
  return `
    <div class="list-item" style="margin-bottom:var(--space-xs);">
      <div style="width:48px;height:48px;background:${color}22;border:1px solid ${color}44;border-radius:var(--radius-md);display:flex;align-items:center;justify-content:center;">
        <span style="font-size:0.7rem;font-weight:700;color:${color};letter-spacing:0.05em;">${code}</span>
      </div>
      <div class="list-content">
        <div class="list-title" style="font-size:0.82rem;">${name}</div>
        <div style="display:flex;align-items:center;gap:6px;margin-top:4px;">
          <div style="flex:1;height:4px;background:var(--ck-surface-elevated);border-radius:2px;overflow:hidden;">
            <div style="width:${pct}%;height:100%;background:${color};border-radius:2px;transition:width 600ms ease;"></div>
          </div>
          <span style="font-size:0.68rem;color:#71717a;">${pct}%</span>
        </div>
      </div>
      <div style="text-align:right;">
        <div style="font-size:0.78rem;font-weight:600;color:#fff;">${active}/${total}</div>
        <div style="display:flex;gap:4px;margin-top:4px;justify-content:flex-end;">
          ${active > 0 ? `<span class="status-dot active"></span>` : ''}
          ${standby > 0 ? `<span class="status-dot standby"></span>` : ''}
          ${error > 0 ? `<span class="status-dot error"></span>` : ''}
        </div>
      </div>
    </div>
  `;
}

function renderSquadBadge(name, role, count, color) {
  return `
    <div class="card" style="padding:var(--space-sm);text-align:center;">
      <div style="font-size:0.65rem;font-weight:700;color:${color};letter-spacing:0.05em;">${name}</div>
      <div style="font-size:1rem;font-weight:700;color:#fff;margin:4px 0;">${count}</div>
      <div style="font-size:0.55rem;color:#71717a;text-transform:uppercase;">${role}</div>
    </div>
  `;
}

function renderEventLog(time, message, color) {
  const dotColor = `var(--ck-${color})`;
  return `
    <div style="display:flex;align-items:flex-start;gap:var(--space-md);padding:var(--space-sm) 0;border-bottom:1px solid var(--ck-border);">
      <div style="min-width:70px;font-size:0.68rem;color:#71717a;">${time}</div>
      <div style="display:flex;align-items:center;gap:var(--space-sm);flex:1;">
        <span class="status-dot" style="background:${dotColor};box-shadow:0 0 6px ${dotColor}33;flex-shrink:0;"></span>
        <span style="font-size:0.75rem;color:#d4d4d8;">${message}</span>
      </div>
    </div>
  `;
}
