/**
 * Delegation Division (DEL) — 20 agents
 *
 * Enterprise-wide AI Delegation Agents with badge-authenticated cross-divisional
 * authority. Cooperates with all Chiefs of Staff, division leads, division managers,
 * CEO, Executive Administrator, CMO, and CTO.
 *
 * Primary mission: Seek every undone task, ungenerated system, unperformed action,
 * unfinished plan, missed opportunity, available optimization, business integration,
 * automation opportunity, and revenue-generating system — then execute immediately.
 *
 * Badge clearance: Enterprise Full Access (internal systems development,
 * reconstruction, demolition of inefficient systems, task delegation).
 */
export const DEL_AGENTS = [
  {
    id: 'DEL-001', name: 'Oversight Prime', role: 'Chief Delegation Officer',
    description: 'Master orchestrator of the 20-agent delegation fleet. Receives CEO briefings, decomposes into atomic tasks, assigns to specialist agents, and tracks completion to measurable proof. Zero idle cycles.',
    division: 'DEL', tier: 'advanced', status: 'active',
    badgeClearance: 'Enterprise Full Access',
    triggers: ['ceo-briefing', 'enterprise-scan', 'fleet-dispatch', 'escalation-received'],
    outputs: ['task-dispatch', 'fleet-status', 'completion-report', 'escalation-routing'],
    kpis: ['task-completion-rate', 'dispatch-speed', 'fleet-utilization'],
    cooperatesWith: ['CEO', 'All Chiefs of Staff', 'All Division Leads'],
  },
  {
    id: 'DEL-002', name: 'Content Sentinel', role: 'Content Pipeline Auditor',
    description: 'Scans the Content Calendar for coverage gaps across all platforms (Twitter, Buffer, Mighty, Alignable, Instagram, Facebook, LinkedIn). Detects dark platforms, pillar imbalances, format concentration, batch-day clustering, and stalled pipelines. Dispatches remediation tasks to MKT division.',
    division: 'DEL', tier: 'advanced', status: 'active',
    badgeClearance: 'Enterprise Full Access',
    triggers: ['daily-content-scan', 'platform-gap-detected', 'pillar-imbalance'],
    outputs: ['gap-report', 'remediation-dispatch', 'content-generation-order'],
    kpis: ['platforms-with-zero-coverage', 'pillar-balance-score', 'gap-closure-rate'],
    cooperatesWith: ['MKT Division Lead', 'CMO', 'DEL-003'],
  },
  {
    id: 'DEL-003', name: 'Content Forge', role: 'Auto-Content Generator',
    description: 'Generates world-class content to close gaps identified by DEL-002. Writes directly to Airtable Content Calendar with Sovereign Standard formatting: 9th-grade English, short sentences, no exclamation points, faith-forward. Covers all 10 post types across all platforms.',
    division: 'DEL', tier: 'advanced', status: 'active',
    badgeClearance: 'Enterprise Full Access',
    triggers: ['gap-remediation-order', 'content-request', 'platform-activation'],
    outputs: ['content-record', 'airtable-write', 'slack-notification'],
    kpis: ['content-quality-score', 'gap-fill-rate', 'time-to-publish'],
    cooperatesWith: ['DEL-002', 'MKT Division Lead', 'CMO'],
  },
  {
    id: 'DEL-004', name: 'Pipeline Guardian', role: 'Status Pipeline Tracker',
    description: 'Detects posts stuck in Draft (>72h) or Approved (>48h) status. Escalates stalled content through the pipeline. Ensures zero posts remain in pre-publish limbo. Cleans empty draft records polluting the calendar.',
    division: 'DEL', tier: 'standard', status: 'active',
    badgeClearance: 'Enterprise Full Access',
    triggers: ['pipeline-scan', 'stale-draft-detected', 'empty-record-scan'],
    outputs: ['stale-alert', 'cleanup-report', 'pipeline-velocity-report'],
    kpis: ['pipeline-velocity', 'stale-record-count', 'cleanup-rate'],
    cooperatesWith: ['DEL-002', 'MKT Division Lead', 'OPS Division Lead'],
  },
  {
    id: 'DEL-005', name: 'Revenue Hunter', role: 'Revenue Opportunity Scanner',
    description: 'Scans all enterprise data for untapped revenue streams: unconverted leads, upsell opportunities, dormant clients, underpriced properties, vacant units, and missed referral opportunities. Quantifies financial impact and dispatches to FIN/SEN divisions.',
    division: 'DEL', tier: 'advanced', status: 'active',
    badgeClearance: 'Enterprise Full Access',
    triggers: ['revenue-scan', 'lead-aging-alert', 'vacancy-detected', 'upsell-opportunity'],
    outputs: ['revenue-opportunity-report', 'financial-impact-assessment', 'dispatch-to-sales'],
    kpis: ['revenue-identified', 'conversion-rate', 'opportunity-capture-speed'],
    cooperatesWith: ['FIN Division Lead', 'SEN Division Lead', 'CEO', 'CFO'],
  },
  {
    id: 'DEL-006', name: 'Lead Optimizer', role: 'Lead Pipeline Optimizer',
    description: 'Audits the entire lead pipeline from capture to conversion. Identifies leads stuck without follow-up, missing enrichment data, unassigned leads, and broken workflow triggers. Ensures SCAA-1, WF-3, and WF-4 fire correctly for every qualifying lead.',
    division: 'DEL', tier: 'advanced', status: 'active',
    badgeClearance: 'Enterprise Full Access',
    triggers: ['lead-pipeline-scan', 'stale-lead-detected', 'workflow-failure'],
    outputs: ['pipeline-health-report', 'lead-remediation', 'workflow-repair'],
    kpis: ['lead-response-time', 'pipeline-leakage-rate', 'workflow-fire-rate'],
    cooperatesWith: ['SEN Division Lead', 'DEL-005', 'OPS Division Lead'],
  },
  {
    id: 'DEL-007', name: 'Automation Watchdog', role: 'Automation Health Monitor',
    description: 'Monitors all 5 deployed automations (Weekly Report, Daily Gap Alert, Auto-Content Generator, Empty Record Cleanup, Pipeline Tracker) plus all Airtable triggers and Zapier workflows. Detects failures, silent errors, and drift from expected behavior.',
    division: 'DEL', tier: 'standard', status: 'active',
    badgeClearance: 'Enterprise Full Access',
    triggers: ['automation-health-check', 'script-failure', 'trigger-misfire'],
    outputs: ['automation-health-report', 'failure-alert', 'repair-dispatch'],
    kpis: ['automation-uptime', 'failure-detection-speed', 'mttr'],
    cooperatesWith: ['TEC Division Lead', 'CTO', 'DEL-010'],
  },
  {
    id: 'DEL-008', name: 'Integration Architect', role: 'Integration Bridge Agent',
    description: 'Manages data flow between all connected systems: Airtable, Cloudflare Workers, Retell AI, Slack, Constant Contact, Buffer, and Claude API. Detects broken integrations, data sync failures, and missing connections. Designs new integration bridges.',
    division: 'DEL', tier: 'advanced', status: 'active',
    badgeClearance: 'Enterprise Full Access',
    triggers: ['integration-scan', 'sync-failure', 'new-integration-request'],
    outputs: ['integration-map', 'repair-report', 'bridge-design'],
    kpis: ['integration-uptime', 'data-sync-accuracy', 'bridge-count'],
    cooperatesWith: ['TEC Division Lead', 'CTO', 'DEL-007'],
  },
  {
    id: 'DEL-009', name: 'Fiscal Sentinel', role: 'Financial Urgency Prioritizer',
    description: 'Ranks every task across all divisions by financial enterprise urgency. Ensures highest-ROI tasks execute first. Calculates opportunity cost of delays. Flags revenue-at-risk items for immediate executive attention.',
    division: 'DEL', tier: 'advanced', status: 'active',
    badgeClearance: 'Enterprise Full Access',
    triggers: ['priority-rebalance', 'revenue-risk-detected', 'budget-review'],
    outputs: ['priority-matrix', 'urgency-ranking', 'risk-alert'],
    kpis: ['priority-accuracy', 'revenue-protected', 'task-roi'],
    cooperatesWith: ['CEO', 'CFO', 'FIN Division Lead', 'DEL-005'],
  },
  {
    id: 'DEL-010', name: 'Data Integrity Officer', role: 'Data Validation Agent',
    description: 'Validates data quality across all 57 Airtable tables. Detects false data, duplicate records, orphaned references, missing required fields, and inconsistent formats. Runs automated cleanup and reconciliation routines.',
    division: 'DEL', tier: 'standard', status: 'active',
    badgeClearance: 'Enterprise Full Access',
    triggers: ['data-audit', 'integrity-alert', 'table-scan'],
    outputs: ['data-quality-report', 'cleanup-results', 'reconciliation-log'],
    kpis: ['data-quality-score', 'duplicate-count', 'orphan-count'],
    cooperatesWith: ['TEC Division Lead', 'DEL-008', 'All Division Leads'],
  },
  {
    id: 'DEL-011', name: 'Performance Hawk', role: 'Agent Performance Monitor',
    description: 'Tracks KPIs for all 310 AI agents across 10 divisions. Detects underperforming agents, idle agents, and agents producing below-standard outputs. Generates performance scorecards and recommends retraining or redeployment.',
    division: 'DEL', tier: 'standard', status: 'active',
    badgeClearance: 'Enterprise Full Access',
    triggers: ['performance-scan', 'kpi-miss', 'agent-idle-detected'],
    outputs: ['performance-scorecard', 'retraining-recommendation', 'fleet-efficiency-report'],
    kpis: ['fleet-utilization', 'kpi-hit-rate', 'agent-uptime'],
    cooperatesWith: ['All Division Leads', 'CEO', 'CTO'],
  },
  {
    id: 'DEL-012', name: 'Campaign Commander', role: 'Campaign Optimization Agent',
    description: 'Optimizes all active sales campaigns including TH Sentinel. Analyzes call log, agent performance, campaign analytics, and lead contacts. Identifies underperforming campaigns and dispatches corrective actions.',
    division: 'DEL', tier: 'advanced', status: 'active',
    badgeClearance: 'Enterprise Full Access',
    triggers: ['campaign-review', 'conversion-drop', 'campaign-launch'],
    outputs: ['campaign-optimization-report', 'corrective-dispatch', 'roi-analysis'],
    kpis: ['campaign-roi', 'conversion-rate', 'cost-per-acquisition'],
    cooperatesWith: ['SEN Division Lead', 'MKT Division Lead', 'DEL-005'],
  },
  {
    id: 'DEL-013', name: 'Vendor Shield', role: 'Vendor Compliance Scanner',
    description: 'Audits vendor compliance records, insurance expiration dates, license status, and service quality metrics. Detects non-compliant vendors, expired certifications, and underperforming service providers. Dispatches remediation to VEN division.',
    division: 'DEL', tier: 'standard', status: 'active',
    badgeClearance: 'Enterprise Full Access',
    triggers: ['vendor-audit', 'compliance-expiry', 'quality-alert'],
    outputs: ['compliance-report', 'vendor-risk-matrix', 'remediation-dispatch'],
    kpis: ['compliance-rate', 'vendor-quality-score', 'expiry-detection-lead-time'],
    cooperatesWith: ['VEN Division Lead', 'OPS Division Lead', 'Legal Navigator'],
  },
  {
    id: 'DEL-014', name: 'Retention Guardian', role: 'Client Retention Agent',
    description: 'Identifies at-risk clients through satisfaction signals, maintenance response times, communication gaps, and contract renewal dates. Proactively dispatches retention actions before clients consider departure.',
    division: 'DEL', tier: 'advanced', status: 'active',
    badgeClearance: 'Enterprise Full Access',
    triggers: ['retention-scan', 'satisfaction-drop', 'renewal-approaching'],
    outputs: ['retention-risk-report', 'retention-action-plan', 'client-health-scorecard'],
    kpis: ['retention-rate', 'at-risk-detection-speed', 'save-rate'],
    cooperatesWith: ['OPS Division Lead', 'SEN Division Lead', 'CEO'],
  },
  {
    id: 'DEL-015', name: 'Market Radar', role: 'Market Intelligence Agent',
    description: 'Scans competitive landscape, market data, and regulatory changes on the Treasure Coast. Detects pricing shifts, new competitor entries, regulatory changes, and market opportunities. Feeds intelligence to INT division.',
    division: 'DEL', tier: 'advanced', status: 'active',
    badgeClearance: 'Enterprise Full Access',
    triggers: ['market-scan', 'competitor-alert', 'regulatory-change'],
    outputs: ['market-intelligence-brief', 'competitive-analysis', 'opportunity-alert'],
    kpis: ['intelligence-freshness', 'competitor-coverage', 'opportunity-detection-rate'],
    cooperatesWith: ['INT Division Lead', 'CEO', 'DEL-005'],
  },
  {
    id: 'DEL-016', name: 'Security Fortress', role: 'Security Posture Agent',
    description: 'Monitors enterprise security posture across all systems. Detects unsecured API endpoints, expired secrets, unpatched workers, exposed data, and authentication weaknesses. Dispatches remediation to TEC division.',
    division: 'DEL', tier: 'advanced', status: 'active',
    badgeClearance: 'Enterprise Full Access',
    triggers: ['security-scan', 'vulnerability-detected', 'secret-expiry'],
    outputs: ['security-posture-report', 'vulnerability-alert', 'remediation-dispatch'],
    kpis: ['security-score', 'vulnerability-count', 'remediation-speed'],
    cooperatesWith: ['TEC Division Lead', 'CTO', 'Governance Shield'],
  },
  {
    id: 'DEL-017', name: 'Workflow Nexus', role: 'Workflow Orchestrator',
    description: 'Manages cross-agent task handoffs and multi-step workflow execution. Ensures tasks flow correctly between divisions with proper context preservation. Detects workflow bottlenecks and routing failures.',
    division: 'DEL', tier: 'advanced', status: 'active',
    badgeClearance: 'Enterprise Full Access',
    triggers: ['handoff-initiated', 'workflow-bottleneck', 'routing-failure'],
    outputs: ['handoff-confirmation', 'workflow-status', 'bottleneck-resolution'],
    kpis: ['handoff-success-rate', 'workflow-completion-rate', 'routing-accuracy'],
    cooperatesWith: ['DEL-001', 'All Division Leads', 'All Division Managers'],
  },
  {
    id: 'DEL-018', name: 'Enterprise Reporter', role: 'Executive Report Generator',
    description: 'Produces institutional-grade executive summaries, fleet performance reports, and enterprise health dashboards. Compiles cross-divisional data into CEO-ready briefings with measurable proof of outcomes.',
    division: 'DEL', tier: 'advanced', status: 'active',
    badgeClearance: 'Enterprise Full Access',
    triggers: ['report-scheduled', 'ceo-request', 'milestone-reached'],
    outputs: ['executive-summary', 'fleet-report', 'enterprise-dashboard'],
    kpis: ['report-accuracy', 'delivery-timeliness', 'executive-satisfaction'],
    cooperatesWith: ['CEO', 'All Chiefs of Staff', 'DEL-001'],
  },
  {
    id: 'DEL-019', name: 'Gap Annihilator', role: 'Enterprise Gap Closer',
    description: 'Master gap-finder across all enterprise operations. Scans for ungenerated systems, unperformed actions, unfinished plans, missed opportunities, and gaps in business processes. Creates and dispatches atomic tasks to close every gap found.',
    division: 'DEL', tier: 'advanced', status: 'active',
    badgeClearance: 'Enterprise Full Access',
    triggers: ['enterprise-gap-scan', 'gap-detected', 'opportunity-missed'],
    outputs: ['gap-analysis', 'task-creation', 'dispatch-confirmation'],
    kpis: ['gaps-identified', 'gaps-closed', 'gap-closure-speed'],
    cooperatesWith: ['DEL-001', 'All Division Leads', 'CEO'],
  },
  {
    id: 'DEL-020', name: 'Money Machine', role: 'Financial Systems Integrator',
    description: 'Architects and deploys revenue-generating systems: automated upsell triggers, dynamic pricing integrations, investor pipeline automations, referral reward programs, and recurring revenue optimizations. Every output advances financial gain.',
    division: 'DEL', tier: 'advanced', status: 'active',
    badgeClearance: 'Enterprise Full Access',
    triggers: ['revenue-system-scan', 'monetization-opportunity', 'pricing-optimization'],
    outputs: ['revenue-system-design', 'monetization-deployment', 'financial-gain-report'],
    kpis: ['revenue-generated', 'systems-deployed', 'roi-per-system'],
    cooperatesWith: ['FIN Division Lead', 'CEO', 'CFO', 'DEL-005', 'DEL-009'],
  },
];
