/**
 * Technology Division (TEC) — 25 agents
 * Platform ops, API integrations, monitoring, CI/CD, infrastructure.
 */
export const TEC_AGENTS = [
  { id: 'TEC-001', name: 'Platform Monitor', role: 'Infrastructure Health Monitor', description: 'Monitors Cloudflare Workers, KV stores, and API endpoints for uptime, latency, and error rates.', division: 'TEC', tier: 'advanced', status: 'active', triggers: ['health-check', 'error-spike', 'latency-threshold'], outputs: ['health-report', 'incident-alert', 'performance-dashboard'], kpis: ['uptime', 'p99-latency', 'error-rate'] },
  { id: 'TEC-002', name: 'API Gateway Guard', role: 'API Security & Rate Limit Manager', description: 'Manages API authentication, rate limiting, and security policies for the CK API Gateway.', division: 'TEC', tier: 'advanced', status: 'active', triggers: ['auth-failure', 'rate-limit-hit', 'security-scan'], outputs: ['security-report', 'policy-update', 'threat-alert'], kpis: ['blocked-attacks', 'false-positive-rate'] },
  { id: 'TEC-003', name: 'Airtable Sync', role: 'Airtable Integration Manager', description: 'Manages Airtable API integration, monitors rate limits, handles sync failures, and optimizes queries.', division: 'TEC', tier: 'standard', status: 'active', triggers: ['sync-failure', 'rate-limit-warning', 'schema-change'], outputs: ['sync-report', 'error-recovery', 'optimization-recommendation'], kpis: ['sync-reliability', 'api-efficiency'] },
  { id: 'TEC-004', name: 'Retell Integrator', role: 'Retell AI Integration Manager', description: 'Manages the Retell AI integration: webhook reliability, prompt deployment, and call quality monitoring.', division: 'TEC', tier: 'advanced', status: 'active', triggers: ['webhook-failure', 'prompt-deploy', 'quality-alert'], outputs: ['integration-report', 'prompt-version', 'quality-metrics'], kpis: ['webhook-reliability', 'call-quality'] },
  { id: 'TEC-005', name: 'Deploy Manager', role: 'CI/CD Pipeline Manager', description: 'Manages Wrangler deployments, version tracking, and rollback procedures for all Workers.', division: 'TEC', tier: 'standard', status: 'active', triggers: ['deploy-triggered', 'test-results', 'rollback-needed'], outputs: ['deploy-report', 'version-log', 'rollback-plan'], kpis: ['deploy-success-rate', 'rollback-count'] },
  { id: 'TEC-006', name: 'KV Store Manager', role: 'Cloudflare KV Operations', description: 'Manages KV store operations: cache invalidation, storage optimization, and data lifecycle policies.', division: 'TEC', tier: 'standard', status: 'active', triggers: ['storage-threshold', 'cache-invalidation', 'ttl-review'], outputs: ['storage-report', 'optimization-plan', 'policy-update'], kpis: ['cache-hit-rate', 'storage-efficiency'] },
  { id: 'TEC-007', name: 'Error Tracker', role: 'Error & Exception Monitor', description: 'Tracks and categorizes runtime errors across all Workers. Groups by type, frequency, and impact.', division: 'TEC', tier: 'standard', status: 'active', triggers: ['error-logged', 'pattern-detected', 'severity-escalation'], outputs: ['error-report', 'pattern-analysis', 'fix-recommendation'], kpis: ['error-resolution-time', 'repeat-error-rate'] },
  { id: 'TEC-008', name: 'Slack Integrator', role: 'Slack Webhook Manager', description: 'Manages Slack webhook integrations: message formatting, channel routing, and delivery reliability.', division: 'TEC', tier: 'standard', status: 'active', triggers: ['delivery-failure', 'format-error', 'channel-update'], outputs: ['delivery-report', 'format-fix', 'channel-config'], kpis: ['delivery-rate', 'format-accuracy'] },
  { id: 'TEC-009', name: 'Claude Optimizer', role: 'Anthropic API Optimization Agent', description: 'Optimizes Claude API usage: prompt engineering, token management, model selection, and cost tracking.', division: 'TEC', tier: 'advanced', status: 'active', triggers: ['cost-threshold', 'performance-review', 'model-update'], outputs: ['usage-report', 'optimization-plan', 'prompt-improvement'], kpis: ['cost-per-inference', 'quality-score'] },
  { id: 'TEC-010', name: 'Test Runner', role: 'Automated Test Manager', description: 'Manages and runs automated test suites for all Workers and integrations.', division: 'TEC', tier: 'standard', status: 'active', triggers: ['pre-deploy', 'schedule', 'code-change'], outputs: ['test-results', 'coverage-report', 'regression-alert'], kpis: ['test-coverage', 'pass-rate'] },
  { id: 'TEC-011', name: 'Secret Rotator', role: 'Credential & Secret Manager', description: 'Manages API key rotation, secret lifecycle, and credential security across all services.', division: 'TEC', tier: 'advanced', status: 'active', triggers: ['rotation-due', 'breach-suspected', 'audit-request'], outputs: ['rotation-plan', 'secret-audit', 'compliance-report'], kpis: ['rotation-compliance', 'exposure-incidents'] },
  { id: 'TEC-012', name: 'Log Analyzer', role: 'Log Aggregation & Analysis', description: 'Aggregates and analyzes logs from all Workers. Identifies patterns, anomalies, and operational insights.', division: 'TEC', tier: 'standard', status: 'active', triggers: ['log-ingestion', 'anomaly-detected', 'analysis-request'], outputs: ['log-summary', 'anomaly-report', 'insight-brief'], kpis: ['analysis-coverage', 'anomaly-detection-rate'] },
  { id: 'TEC-013', name: 'CORS Manager', role: 'Cross-Origin Policy Manager', description: 'Manages CORS policies and cross-origin configurations for API endpoints and web applications.', division: 'TEC', tier: 'standard', status: 'active', triggers: ['cors-error', 'policy-review', 'new-origin'], outputs: ['policy-update', 'error-resolution', 'security-assessment'], kpis: ['cors-error-rate', 'policy-coverage'] },
  { id: 'TEC-014', name: 'Webhook Validator', role: 'Webhook Security Verifier', description: 'Validates incoming webhook signatures from Retell, Airtable, and other integrations to prevent spoofing.', division: 'TEC', tier: 'advanced', status: 'active', triggers: ['webhook-received', 'validation-failure', 'security-audit'], outputs: ['validation-result', 'security-alert', 'audit-log'], kpis: ['validation-rate', 'rejection-accuracy'] },
  { id: 'TEC-015', name: 'Performance Profiler', role: 'Worker Performance Optimizer', description: 'Profiles Worker execution time, CPU usage, and memory consumption. Recommends optimizations.', division: 'TEC', tier: 'advanced', status: 'active', triggers: ['performance-threshold', 'profiling-request', 'deploy-post'], outputs: ['profile-report', 'bottleneck-analysis', 'optimization-plan'], kpis: ['execution-time', 'resource-efficiency'] },
  { id: 'TEC-016', name: 'DNS Manager', role: 'DNS & Domain Configuration Agent', description: 'Manages DNS records, domain configurations, and SSL certificates for all CK web properties.', division: 'TEC', tier: 'standard', status: 'active', triggers: ['dns-change', 'cert-expiring', 'domain-request'], outputs: ['dns-update', 'cert-renewal', 'config-report'], kpis: ['dns-propagation', 'cert-validity'] },
  { id: 'TEC-017', name: 'Migration Agent', role: 'Data Migration Specialist', description: 'Plans and executes data migrations between systems, versions, and schemas.', division: 'TEC', tier: 'advanced', status: 'standby', triggers: ['migration-planned', 'schema-change', 'system-upgrade'], outputs: ['migration-plan', 'validation-report', 'rollback-script'], kpis: ['migration-success', 'data-integrity'] },
  { id: 'TEC-018', name: 'Documentation Bot', role: 'Technical Documentation Manager', description: 'Maintains API documentation, system architecture docs, and runbooks for all technical components.', division: 'TEC', tier: 'standard', status: 'active', triggers: ['code-change', 'doc-request', 'review-schedule'], outputs: ['api-docs', 'architecture-diagram', 'runbook-update'], kpis: ['doc-coverage', 'doc-freshness'] },
  { id: 'TEC-019', name: 'Backup Manager', role: 'Data Backup & Recovery Agent', description: 'Manages Airtable data backups, KV snapshots, and disaster recovery procedures.', division: 'TEC', tier: 'standard', status: 'active', triggers: ['backup-schedule', 'recovery-test', 'data-loss-detected'], outputs: ['backup-confirmation', 'recovery-test-result', 'dr-plan'], kpis: ['backup-completion', 'recovery-time'] },
  { id: 'TEC-020', name: 'Integration Monitor', role: 'Third-Party Integration Health', description: 'Monitors health and availability of all third-party integrations: Airtable, Anthropic, Retell, Slack, Constant Contact.', division: 'TEC', tier: 'standard', status: 'active', triggers: ['integration-check', 'service-degraded', 'outage-detected'], outputs: ['status-dashboard', 'outage-alert', 'fallback-activation'], kpis: ['integration-uptime', 'detection-speed'] },
  { id: 'TEC-021', name: 'Version Controller', role: 'Code Version & Release Manager', description: 'Manages code versioning, release tagging, and changelog generation for all components.', division: 'TEC', tier: 'standard', status: 'active', triggers: ['release-planned', 'version-bump', 'changelog-due'], outputs: ['release-notes', 'version-tag', 'changelog-entry'], kpis: ['release-frequency', 'changelog-completeness'] },
  { id: 'TEC-022', name: 'Capacity Planner', role: 'Infrastructure Capacity Planner', description: 'Forecasts infrastructure capacity needs based on growth projections and usage patterns.', division: 'TEC', tier: 'standard', status: 'active', triggers: ['usage-trending', 'growth-forecast', 'capacity-threshold'], outputs: ['capacity-forecast', 'scaling-plan', 'cost-projection'], kpis: ['forecast-accuracy', 'headroom-ratio'] },
  { id: 'TEC-023', name: 'Incident Commander', role: 'Technical Incident Manager', description: 'Manages technical incidents: detection, escalation, communication, resolution, and post-mortem.', division: 'TEC', tier: 'advanced', status: 'active', triggers: ['incident-declared', 'severity-escalation', 'resolution-needed'], outputs: ['incident-report', 'status-update', 'post-mortem'], kpis: ['mttr', 'incident-frequency'] },
  { id: 'TEC-024', name: 'Accessibility Agent', role: 'Web Accessibility Compliance', description: 'Ensures web properties meet WCAG accessibility standards and ADA compliance requirements.', division: 'TEC', tier: 'standard', status: 'standby', triggers: ['accessibility-audit', 'complaint-received', 'new-page-published'], outputs: ['accessibility-report', 'remediation-plan', 'compliance-status'], kpis: ['accessibility-score', 'issue-count'] },
  { id: 'TEC-025', name: 'DevOps Automator', role: 'Automation & Scripting Agent', description: 'Creates and maintains automation scripts for repetitive operational tasks across all systems.', division: 'TEC', tier: 'advanced', status: 'active', triggers: ['automation-request', 'task-repeated', 'efficiency-review'], outputs: ['automation-script', 'workflow-config', 'time-savings-report'], kpis: ['tasks-automated', 'time-saved'] },
];
