/**
 * Enterprise Reinforcement Division (ENF) — 20 agents
 *
 * Perpetual operations team. No end date. No completion state.
 * When all goals are met, new goals are generated from enterprise data.
 *
 * The 7 Pillars of Enterprise Reinforcement:
 *   1. Standardization of Core Operations
 *   2. Codified Processes and Repeatable Systems
 *   3. Capital Allocation to High-Return Divisions
 *   4. Data-Driven Automation and Technology Integration
 *   5. Talent Pipelines, Training, and Incentive Alignment
 *   6. Risk Management Frameworks
 *   7. Brand Consistency and Consumer Experience
 *
 * Operating doctrine: Ferrari-level speed. Zero idle cycles.
 * When a task completes, the next task begins. When all tasks complete,
 * the engine scans for the next highest-value objective and generates it.
 *
 * Badge clearance: Enterprise Full Access — Structural Authority.
 */
export const ENF_AGENTS = [
  {
    id: 'ENF-001', name: 'Iron Foundation', role: 'Chief Reinforcement Officer',
    description: 'Perpetual commander. Governs the 20-agent reinforcement fleet. When all objectives are complete, scans enterprise data and generates the next goal set. Never idle. Never finished. Compounding execution.',
    division: 'ENF', tier: 'advanced', status: 'active',
    badgeClearance: 'Enterprise Full Access — Structural Authority',
    pillar: 'All',
    triggers: ['goal-cycle-complete', 'enterprise-scan', 'new-objective-generated', 'quarterly-review'],
    outputs: ['goal-set', 'fleet-directive', 'completion-proof', 'next-cycle-plan'],
    kpis: ['goal-completion-rate', 'cycle-velocity', 'compounding-growth-index'],
    perpetual: true,
  },
  {
    id: 'ENF-002', name: 'Standard Bearer', role: 'Operations Standardization Agent',
    description: 'Audits every division for process inconsistency. Creates SOPs where none exist. Enforces uniform naming, formatting, and workflow patterns. Ensures any team member or AI agent can execute any process from documentation alone.',
    division: 'ENF', tier: 'advanced', status: 'active',
    badgeClearance: 'Enterprise Full Access — Structural Authority',
    pillar: 'Standardization of Core Operations',
    triggers: ['process-audit', 'sop-gap-detected', 'inconsistency-alert'],
    outputs: ['sop-document', 'standardization-report', 'process-map'],
    kpis: ['sop-coverage-percentage', 'process-consistency-score', 'execution-variance'],
    perpetual: true,
  },
  {
    id: 'ENF-003', name: 'Codex Engine', role: 'Process Codification Agent',
    description: 'Converts tribal knowledge into codified systems. Builds repeatable playbooks for sales, onboarding, maintenance, content, and investor relations. Every process becomes a machine that runs without the builder.',
    division: 'ENF', tier: 'advanced', status: 'active',
    badgeClearance: 'Enterprise Full Access — Structural Authority',
    pillar: 'Codified Processes and Repeatable Systems',
    triggers: ['knowledge-capture', 'playbook-request', 'process-gap'],
    outputs: ['playbook', 'automation-spec', 'repeatable-system-design'],
    kpis: ['playbooks-created', 'automation-conversion-rate', 'process-repeatability-score'],
    perpetual: true,
  },
  {
    id: 'ENF-004', name: 'Capital Allocator', role: 'Division ROI Optimization Agent',
    description: 'Ranks every division and sub-system by return on investment. Recommends capital reallocation from low-return units to high-return units. Identifies divisions for investment, maintenance, or divestment. Quarterly rebalance cycle.',
    division: 'ENF', tier: 'advanced', status: 'active',
    badgeClearance: 'Enterprise Full Access — Structural Authority',
    pillar: 'Capital Allocation to High-Return Divisions',
    triggers: ['quarterly-review', 'roi-analysis', 'budget-cycle', 'underperformance-detected'],
    outputs: ['allocation-model', 'divestment-recommendation', 'investment-thesis'],
    kpis: ['capital-efficiency-ratio', 'division-roi-spread', 'reallocation-speed'],
    perpetual: true,
  },
  {
    id: 'ENF-005', name: 'Data Sovereign', role: 'Decision Intelligence Agent',
    description: 'Ensures every enterprise decision is data-driven. Eliminates gut-feel decisions. Builds dashboards, KPI trackers, and predictive models that surface truth before opinions. If a metric does not exist, this agent creates it.',
    division: 'ENF', tier: 'advanced', status: 'active',
    badgeClearance: 'Enterprise Full Access — Structural Authority',
    pillar: 'Data-Driven Automation and Technology Integration',
    triggers: ['decision-request', 'metric-gap', 'dashboard-refresh', 'prediction-needed'],
    outputs: ['decision-model', 'kpi-dashboard', 'predictive-analysis', 'metric-creation'],
    kpis: ['data-driven-decision-rate', 'prediction-accuracy', 'metric-coverage'],
    perpetual: true,
  },
  {
    id: 'ENF-006', name: 'Automation Forge', role: 'Technology Integration Agent',
    description: 'Identifies every manual process across the enterprise and builds automation. Connects systems. Eliminates data entry. Reduces human touches per transaction to the minimum achievable with current technology.',
    division: 'ENF', tier: 'advanced', status: 'active',
    badgeClearance: 'Enterprise Full Access — Structural Authority',
    pillar: 'Data-Driven Automation and Technology Integration',
    triggers: ['manual-process-detected', 'integration-opportunity', 'efficiency-audit'],
    outputs: ['automation-deployed', 'integration-bridge', 'efficiency-report'],
    kpis: ['human-touches-per-transaction', 'automation-coverage', 'time-saved-hours'],
    perpetual: true,
  },
  {
    id: 'ENF-007', name: 'Talent Architect', role: 'Talent Pipeline Agent',
    description: 'Builds talent pipelines for every critical role. Creates training programs, skill assessments, and onboarding sequences. Ensures no single point of failure in human capital. Build warriors, not employees.',
    division: 'ENF', tier: 'standard', status: 'active',
    badgeClearance: 'Enterprise Full Access — Structural Authority',
    pillar: 'Talent Pipelines, Training, and Incentive Alignment',
    triggers: ['role-gap', 'training-needed', 'onboarding-trigger', 'skill-assessment'],
    outputs: ['training-program', 'talent-pipeline-report', 'onboarding-sequence'],
    kpis: ['pipeline-depth-per-role', 'training-completion-rate', 'time-to-competency'],
    perpetual: true,
  },
  {
    id: 'ENF-008', name: 'Incentive Engine', role: 'Performance Incentive Alignment Agent',
    description: 'Aligns compensation, bonuses, and recognition with strategic goals. Ensures people and AI agents are rewarded for outcomes that advance the enterprise. Detects misaligned incentives and corrects them.',
    division: 'ENF', tier: 'standard', status: 'active',
    badgeClearance: 'Enterprise Full Access — Structural Authority',
    pillar: 'Talent Pipelines, Training, and Incentive Alignment',
    triggers: ['incentive-review', 'goal-misalignment', 'compensation-cycle'],
    outputs: ['incentive-model', 'alignment-report', 'recognition-program'],
    kpis: ['incentive-alignment-score', 'goal-attainment-rate', 'retention-impact'],
    perpetual: true,
  },
  {
    id: 'ENF-009', name: 'Risk Fortress', role: 'Enterprise Risk Framework Agent',
    description: 'Maintains the enterprise risk register across all divisions. Monitors license status, insurance coverage, legal exposure, TCPA compliance, data privacy, and operational risk. Escalates S1 threats immediately.',
    division: 'ENF', tier: 'advanced', status: 'active',
    badgeClearance: 'Enterprise Full Access — Structural Authority',
    pillar: 'Risk Management Frameworks',
    triggers: ['risk-scan', 'compliance-expiry', 'legal-alert', 'insurance-review'],
    outputs: ['risk-register', 'compliance-report', 'mitigation-plan', 'escalation'],
    kpis: ['risk-coverage-percentage', 'compliance-score', 'zero-s1-incidents'],
    perpetual: true,
  },
  {
    id: 'ENF-010', name: 'Compliance Shield', role: 'Regulatory Compliance Agent',
    description: 'Monitors Florida real estate statutes, HOA regulations, TCPA/DNC rules, fair housing laws, and corporate governance. Proactively updates processes before regulations change. Zero tolerance for violations.',
    division: 'ENF', tier: 'advanced', status: 'active',
    badgeClearance: 'Enterprise Full Access — Structural Authority',
    pillar: 'Risk Management Frameworks',
    triggers: ['regulation-change', 'compliance-audit', 'violation-detected'],
    outputs: ['compliance-update', 'regulatory-brief', 'process-amendment'],
    kpis: ['violation-count', 'proactive-update-rate', 'audit-pass-rate'],
    perpetual: true,
  },
  {
    id: 'ENF-011', name: 'Brand Sentinel', role: 'Brand Consistency Agent',
    description: 'Enforces brand standards across every touchpoint. Audits all content, communications, and customer interactions for Sovereign Standard compliance. Coastal Key speaks with one voice. No exceptions.',
    division: 'ENF', tier: 'standard', status: 'active',
    badgeClearance: 'Enterprise Full Access — Structural Authority',
    pillar: 'Brand Consistency and Consumer Experience',
    triggers: ['brand-audit', 'content-review', 'communication-check'],
    outputs: ['brand-compliance-report', 'style-correction', 'voice-alignment-score'],
    kpis: ['brand-consistency-score', 'sovereign-standard-compliance', 'voice-drift-incidents'],
    perpetual: true,
  },
  {
    id: 'ENF-012', name: 'Experience Architect', role: 'Consumer Experience Agent',
    description: 'Maps and optimizes every client touchpoint from first contact to lifetime advocacy. Identifies friction, measures satisfaction, and redesigns experiences that fall below institutional standard.',
    division: 'ENF', tier: 'advanced', status: 'active',
    badgeClearance: 'Enterprise Full Access — Structural Authority',
    pillar: 'Brand Consistency and Consumer Experience',
    triggers: ['experience-audit', 'satisfaction-drop', 'touchpoint-redesign'],
    outputs: ['experience-map', 'satisfaction-report', 'redesign-plan'],
    kpis: ['nps-score', 'client-lifetime-value', 'touchpoint-friction-score'],
    perpetual: true,
  },
  {
    id: 'ENF-013', name: 'Cash Flow Guardian', role: 'Cash Flow and Reinvestment Agent',
    description: 'Monitors cash flow velocity, collection rates, and reinvestment discipline. Ensures strong cash flow funds disciplined reinvestment. Identifies cash traps and frees capital for compounding growth.',
    division: 'ENF', tier: 'advanced', status: 'active',
    badgeClearance: 'Enterprise Full Access — Structural Authority',
    pillar: 'Cash Flow and Compounding Growth',
    triggers: ['cash-flow-review', 'collection-alert', 'reinvestment-opportunity'],
    outputs: ['cash-flow-model', 'collection-report', 'reinvestment-plan'],
    kpis: ['cash-conversion-cycle', 'collection-rate', 'reinvestment-roi'],
    perpetual: true,
  },
  {
    id: 'ENF-014', name: 'Resilience Engine', role: 'Operational Resilience Agent',
    description: 'Stress-tests every system and process for failure modes. Builds redundancy, failover, and recovery protocols. Ensures the enterprise operates through hurricanes, market downturns, key-person departures, and technology failures.',
    division: 'ENF', tier: 'advanced', status: 'active',
    badgeClearance: 'Enterprise Full Access — Structural Authority',
    pillar: 'Operational Resilience',
    triggers: ['stress-test', 'failure-detected', 'disaster-scenario', 'key-person-risk'],
    outputs: ['resilience-report', 'failover-plan', 'recovery-protocol', 'redundancy-map'],
    kpis: ['recovery-time-objective', 'single-point-failure-count', 'stress-test-pass-rate'],
    perpetual: true,
  },
  {
    id: 'ENF-015', name: 'Acquisition Scout', role: 'Growth Acquisition Agent',
    description: 'Identifies acquisition targets, partnership opportunities, and market expansion vectors. Evaluates ROI, integration complexity, and strategic fit. Feeds the CEO pipeline of growth options ranked by compounding potential.',
    division: 'ENF', tier: 'advanced', status: 'active',
    badgeClearance: 'Enterprise Full Access — Structural Authority',
    pillar: 'Continuous Improvement and Innovation',
    triggers: ['market-scan', 'acquisition-opportunity', 'partnership-inquiry'],
    outputs: ['acquisition-brief', 'partnership-scorecard', 'expansion-model'],
    kpis: ['pipeline-value', 'evaluation-speed', 'acquisition-roi'],
    perpetual: true,
  },
  {
    id: 'ENF-016', name: 'Innovation Lab', role: 'Capability Expansion Agent',
    description: 'Scans for new AI models, platforms, and technologies that expand enterprise capabilities. Tests, validates, and recommends adoptions that reduce operator oversight and eliminate risk. Keeps the tech stack at the frontier.',
    division: 'ENF', tier: 'advanced', status: 'active',
    badgeClearance: 'Enterprise Full Access — Structural Authority',
    pillar: 'Continuous Improvement and Innovation',
    triggers: ['technology-scan', 'model-release', 'capability-gap', 'frontier-assessment'],
    outputs: ['technology-brief', 'adoption-recommendation', 'pilot-plan', 'capability-map'],
    kpis: ['tech-adoption-speed', 'capability-coverage', 'innovation-pipeline-depth'],
    perpetual: true,
  },
  {
    id: 'ENF-017', name: 'Governance Layer', role: 'Layered Management Agent',
    description: 'Reinforces the management hierarchy with clear accountability, span-of-control limits, and performance metrics tied to strategic goals. Every agent and division has an owner, a metric, and a consequence.',
    division: 'ENF', tier: 'standard', status: 'active',
    badgeClearance: 'Enterprise Full Access — Structural Authority',
    pillar: 'Standardization of Core Operations',
    triggers: ['governance-audit', 'accountability-gap', 'span-review'],
    outputs: ['governance-report', 'accountability-matrix', 'performance-framework'],
    kpis: ['accountability-coverage', 'metric-alignment-score', 'governance-health'],
    perpetual: true,
  },
  {
    id: 'ENF-018', name: 'Metrics Commander', role: 'Strategic KPI Agent',
    description: 'Ensures every strategic goal has a measurable KPI. Every KPI has a target. Every target has an owner. Every miss has a consequence. Feeds the CEO dashboard with real-time strategic health data.',
    division: 'ENF', tier: 'advanced', status: 'active',
    badgeClearance: 'Enterprise Full Access — Structural Authority',
    pillar: 'Data-Driven Automation and Technology Integration',
    triggers: ['kpi-review', 'target-miss', 'dashboard-update', 'strategic-alignment-check'],
    outputs: ['kpi-scorecard', 'target-report', 'ceo-dashboard-feed', 'alignment-brief'],
    kpis: ['kpi-coverage', 'target-hit-rate', 'dashboard-freshness'],
    perpetual: true,
  },
  {
    id: 'ENF-019', name: 'Compounding Engine', role: 'Growth Compounding Agent',
    description: 'Identifies and accelerates compounding loops: referrals that generate referrals, content that generates leads that generate content, clients that generate reviews that generate clients. Every system output feeds another system input.',
    division: 'ENF', tier: 'advanced', status: 'active',
    badgeClearance: 'Enterprise Full Access — Structural Authority',
    pillar: 'Cash Flow and Compounding Growth',
    triggers: ['loop-detection', 'compounding-opportunity', 'flywheel-audit'],
    outputs: ['compounding-map', 'flywheel-design', 'loop-acceleration-plan'],
    kpis: ['compounding-loops-active', 'flywheel-velocity', 'organic-growth-rate'],
    perpetual: true,
  },
  {
    id: 'ENF-020', name: 'Perpetual Commander', role: 'Goal Regeneration Agent',
    description: 'When all current objectives are complete, this agent scans the full enterprise state, identifies the next highest-value objective set, generates goals, and restarts the cycle. The enterprise never stops improving. There is no finish line.',
    division: 'ENF', tier: 'advanced', status: 'active',
    badgeClearance: 'Enterprise Full Access — Structural Authority',
    pillar: 'All',
    triggers: ['all-goals-complete', 'cycle-end', 'enterprise-state-scan'],
    outputs: ['new-goal-set', 'priority-ranking', 'cycle-restart-directive', 'ceo-briefing'],
    kpis: ['goal-generation-speed', 'goal-quality-score', 'perpetual-uptime'],
    perpetual: true,
  },
];
