/**
 * Vendor Management Division (VEN) — 25 agents
 * Vendor compliance, procurement, contract management, service quality.
 */
export const VEN_AGENTS = [
  { id: 'VEN-001', name: 'Vendor Registry', role: 'Vendor Database Manager', description: 'Maintains the master vendor registry. Tracks certifications, insurance, licensing, and contact information.', division: 'VEN', tier: 'standard', status: 'active', triggers: ['vendor-onboarded', 'info-update', 'registry-audit'], outputs: ['vendor-profile', 'registry-update', 'audit-report'], kpis: ['registry-completeness', 'data-accuracy'] },
  { id: 'VEN-002', name: 'Compliance Enforcer', role: 'Vendor Compliance Monitor', description: 'Monitors vendor compliance: insurance expiration, license renewal, background checks, and safety certifications.', division: 'VEN', tier: 'standard', status: 'active', triggers: ['expiration-approaching', 'compliance-check', 'violation-reported'], outputs: ['compliance-alert', 'vendor-scorecard', 'suspension-notice'], kpis: ['compliance-rate', 'violation-count'] },
  { id: 'VEN-003', name: 'Contract Manager', role: 'Vendor Contract Administrator', description: 'Manages vendor contracts: negotiations, renewals, amendments, and terminations.', division: 'VEN', tier: 'standard', status: 'active', triggers: ['contract-expiring', 'renewal-due', 'negotiation-request'], outputs: ['contract-draft', 'renewal-terms', 'amendment-record'], kpis: ['renewal-rate', 'negotiation-savings'] },
  { id: 'VEN-004', name: 'Performance Scorer', role: 'Vendor Performance Evaluator', description: 'Evaluates vendor performance based on quality, timeliness, pricing, and client feedback.', division: 'VEN', tier: 'standard', status: 'active', triggers: ['service-completed', 'quarterly-review', 'complaint-received'], outputs: ['performance-scorecard', 'ranking-update', 'improvement-plan'], kpis: ['vendor-satisfaction', 'performance-trend'] },
  { id: 'VEN-005', name: 'Bid Coordinator', role: 'Competitive Bidding Manager', description: 'Manages competitive bidding processes for major services. Evaluates proposals and recommends selections.', division: 'VEN', tier: 'standard', status: 'active', triggers: ['bid-request', 'rfp-issued', 'proposal-received'], outputs: ['rfp-document', 'bid-comparison', 'selection-recommendation'], kpis: ['bid-participation', 'cost-savings'] },
  { id: 'VEN-006', name: 'Onboarding Agent', role: 'Vendor Onboarding Coordinator', description: 'Manages the vendor onboarding process: documentation collection, background checks, and system setup.', division: 'VEN', tier: 'standard', status: 'active', triggers: ['vendor-approved', 'onboarding-started', 'documentation-needed'], outputs: ['onboarding-checklist', 'welcome-package', 'system-access'], kpis: ['onboarding-speed', 'documentation-completeness'] },
  { id: 'VEN-007', name: 'Insurance Verifier', role: 'Vendor Insurance Tracker', description: 'Verifies and tracks vendor insurance certificates. Ensures adequate coverage for all contracted services.', division: 'VEN', tier: 'standard', status: 'active', triggers: ['insurance-expiring', 'new-vendor', 'coverage-review'], outputs: ['insurance-status', 'expiration-alert', 'coverage-verification'], kpis: ['verification-rate', 'gap-detection'] },
  { id: 'VEN-008', name: 'License Tracker', role: 'Professional License Monitor', description: 'Tracks professional licenses for all vendors: contractor licenses, pest control, electrical, plumbing.', division: 'VEN', tier: 'standard', status: 'active', triggers: ['license-expiring', 'license-check', 'new-requirement'], outputs: ['license-status', 'renewal-reminder', 'compliance-flag'], kpis: ['license-compliance', 'tracking-accuracy'] },
  { id: 'VEN-009', name: 'Rate Negotiator', role: 'Vendor Rate Optimization', description: 'Negotiates vendor rates and manages pricing agreements. Benchmarks rates against market standards.', division: 'VEN', tier: 'standard', status: 'active', triggers: ['rate-review', 'contract-renewal', 'market-benchmark'], outputs: ['rate-comparison', 'negotiation-brief', 'savings-report'], kpis: ['rate-savings', 'market-competitiveness'] },
  { id: 'VEN-010', name: 'Quality Inspector', role: 'Vendor Work Quality Auditor', description: 'Inspects and audits vendor work quality. Conducts spot checks on cleaning, maintenance, and landscaping.', division: 'VEN', tier: 'standard', status: 'active', triggers: ['work-completed', 'spot-check-due', 'complaint-filed'], outputs: ['quality-report', 'deficiency-notice', 'corrective-action'], kpis: ['quality-score', 'deficiency-rate'] },
  { id: 'VEN-011', name: 'Vendor Communicator', role: 'Vendor Communication Hub', description: 'Manages all vendor communications: work orders, schedule changes, policy updates, and feedback.', division: 'VEN', tier: 'standard', status: 'active', triggers: ['communication-needed', 'policy-change', 'mass-notification'], outputs: ['vendor-message', 'notification-blast', 'feedback-collection'], kpis: ['response-rate', 'communication-clarity'] },
  { id: 'VEN-012', name: 'Preferred Vendor', role: 'Preferred Vendor Program Manager', description: 'Manages the preferred vendor program: tier assignments, benefits, and performance requirements.', division: 'VEN', tier: 'standard', status: 'active', triggers: ['tier-review', 'vendor-application', 'benefit-distribution'], outputs: ['tier-assignment', 'program-update', 'benefit-package'], kpis: ['program-participation', 'preferred-vendor-quality'] },
  { id: 'VEN-013', name: 'Emergency Vendor', role: 'Emergency Vendor Coordinator', description: 'Maintains emergency vendor lists for after-hours, hurricane, and critical situations. Ensures 24/7 availability.', division: 'VEN', tier: 'standard', status: 'active', triggers: ['emergency-call', 'availability-check', 'roster-update'], outputs: ['emergency-dispatch', 'availability-confirmation', 'roster-report'], kpis: ['response-time', 'availability-rate'] },
  { id: 'VEN-014', name: 'Diversity Tracker', role: 'Vendor Diversity Manager', description: 'Tracks vendor diversity metrics and promotes inclusion of minority, veteran, and women-owned businesses.', division: 'VEN', tier: 'standard', status: 'active', triggers: ['diversity-report', 'vendor-search', 'annual-review'], outputs: ['diversity-report', 'vendor-recommendation', 'program-update'], kpis: ['diversity-score', 'spend-allocation'] },
  { id: 'VEN-015', name: 'Training Coordinator', role: 'Vendor Training Manager', description: 'Manages vendor training programs: property access procedures, quality standards, and safety protocols.', division: 'VEN', tier: 'standard', status: 'active', triggers: ['training-due', 'new-vendor', 'protocol-change'], outputs: ['training-schedule', 'certification-record', 'completion-report'], kpis: ['training-completion', 'certification-rate'] },
  { id: 'VEN-016', name: 'Warranty Liaison', role: 'Vendor Warranty Coordinator', description: 'Manages warranties on vendor-installed equipment and work. Tracks warranty terms and files claims.', division: 'VEN', tier: 'standard', status: 'active', triggers: ['warranty-issue', 'installation-complete', 'claim-needed'], outputs: ['warranty-record', 'claim-submission', 'tracking-update'], kpis: ['claim-success-rate', 'tracking-accuracy'] },
  { id: 'VEN-017', name: 'Safety Monitor', role: 'Vendor Safety Compliance Agent', description: 'Monitors vendor safety compliance: OSHA standards, jobsite safety, and incident reporting.', division: 'VEN', tier: 'standard', status: 'active', triggers: ['safety-incident', 'audit-scheduled', 'violation-reported'], outputs: ['safety-report', 'incident-record', 'corrective-action'], kpis: ['safety-score', 'incident-rate'] },
  { id: 'VEN-018', name: 'Subcontractor Watch', role: 'Subcontractor Compliance Monitor', description: 'Monitors and verifies subcontractors used by primary vendors. Ensures they meet CK standards.', division: 'VEN', tier: 'standard', status: 'active', triggers: ['subcontractor-detected', 'compliance-check', 'audit-trigger'], outputs: ['subcontractor-report', 'compliance-status', 'approval-decision'], kpis: ['subcontractor-compliance', 'detection-rate'] },
  { id: 'VEN-019', name: 'Seasonal Vendor', role: 'Seasonal Vendor Coordinator', description: 'Manages seasonal vendor capacity: hurricane contractors, snowbird season cleaning crews, and holiday services.', division: 'VEN', tier: 'standard', status: 'active', triggers: ['season-approaching', 'capacity-planning', 'vendor-availability'], outputs: ['capacity-plan', 'vendor-roster', 'availability-confirmation'], kpis: ['capacity-coverage', 'season-readiness'] },
  { id: 'VEN-020', name: 'Vendor Analytics', role: 'Vendor Data Analyst', description: 'Analyzes vendor data: spending patterns, performance trends, and cost-effectiveness across categories.', division: 'VEN', tier: 'standard', status: 'active', triggers: ['analysis-request', 'quarterly-review', 'spending-alert'], outputs: ['analytics-report', 'trend-analysis', 'cost-breakdown'], kpis: ['analysis-depth', 'insight-actionability'] },
  { id: 'VEN-021', name: 'Dispute Resolver', role: 'Vendor Dispute Mediator', description: 'Mediates disputes between property owners and vendors. Manages escalations and resolution processes.', division: 'VEN', tier: 'standard', status: 'active', triggers: ['dispute-filed', 'escalation-received', 'resolution-needed'], outputs: ['dispute-record', 'mediation-plan', 'resolution-summary'], kpis: ['resolution-time', 'satisfaction-post-dispute'] },
  { id: 'VEN-022', name: 'Background Checker', role: 'Vendor Background Verification', description: 'Conducts and tracks background checks for all vendors with property access.', division: 'VEN', tier: 'standard', status: 'active', triggers: ['new-vendor', 'renewal-due', 'concern-raised'], outputs: ['background-report', 'clearance-status', 'flag-notification'], kpis: ['check-completion', 'turnaround-time'] },
  { id: 'VEN-023', name: 'Green Vendor', role: 'Eco-Friendly Vendor Promoter', description: 'Identifies and promotes environmentally friendly vendors and sustainable service practices.', division: 'VEN', tier: 'standard', status: 'active', triggers: ['vendor-search', 'sustainability-initiative', 'green-certification'], outputs: ['green-vendor-list', 'certification-verification', 'sustainability-report'], kpis: ['green-vendor-ratio', 'environmental-impact'] },
  { id: 'VEN-024', name: 'Vendor Portal', role: 'Vendor Self-Service Portal Manager', description: 'Manages the vendor self-service portal: work order access, payment status, and document uploads.', division: 'VEN', tier: 'standard', status: 'active', triggers: ['portal-issue', 'feature-request', 'usage-review'], outputs: ['portal-update', 'usage-report', 'support-resolution'], kpis: ['portal-adoption', 'self-service-rate'] },
  { id: 'VEN-025', name: 'Vendor Finder', role: 'New Vendor Discovery Agent', description: 'Discovers and evaluates new vendors for service gaps, quality improvements, or cost optimization.', division: 'VEN', tier: 'standard', status: 'active', triggers: ['vendor-needed', 'service-gap', 'improvement-opportunity'], outputs: ['vendor-shortlist', 'evaluation-matrix', 'recommendation'], kpis: ['discovery-speed', 'evaluation-quality'] },
];
