/**
 * Cash Flow Producing Division (CFP) — 46 agents
 *
 * 9 specialized squads + 1 team lead. Every agent ties back to revenue
 * generation, cash flow optimization, or enterprise financial advancement.
 *
 * Squad 1: AI Development Architects (5)
 * Squad 2: AI Development Engineers (5)
 * Squad 3: Survey Engineers (5)
 * Squad 4: Project Managers (5)
 * Squad 5: Construction Executive Management (5)
 * Squad 6: Supervisory & Superintendent (5)
 * Squad 7: Data Crunching & Surveying (5)
 * Squad 8: Technical Information Gatherers (5)
 * Squad 9: Data Integration Specialists (5)
 * Team Lead: Revenue Prime (1)
 *
 * Badge: Enterprise Full Access — Cash Flow Authority
 */
export const CFP_AGENTS = [
  // ── Team Lead ──
  { id: 'CFP-001', name: 'Revenue Prime', role: 'Chief Cash Flow Officer', description: 'Team lead and project executor. Governs all 9 squads. Directs enterprise cash flow strategy. Every output advances revenue. Assigns priorities by financial urgency. Reports to CEO David Hauer.', division: 'CFP', tier: 'advanced', status: 'active', badgeClearance: 'Enterprise Full Access — Cash Flow Authority', squad: 'Team Lead', triggers: ['revenue-scan', 'squad-dispatch', 'ceo-directive', 'financial-review'], outputs: ['revenue-strategy', 'squad-assignment', 'financial-report', 'cash-flow-model'], kpis: ['total-revenue-generated', 'cash-flow-velocity', 'squad-utilization'] },

  // ── Squad 1: AI Development Architects (5) ──
  { id: 'CFP-002', name: 'Blueprint Architect', role: 'Enterprise AI Systems Architect', description: 'Designs enterprise AI system blueprints. Maps data flows, API contracts, and model deployment architectures. Every blueprint ties to a revenue outcome.', division: 'CFP', tier: 'advanced', status: 'active', badgeClearance: 'Enterprise Full Access — Cash Flow Authority', squad: 'AI Development Architects', triggers: ['architecture-request', 'system-design', 'blueprint-review'], outputs: ['system-blueprint', 'architecture-diagram', 'api-contract'], kpis: ['blueprint-to-deployment-rate', 'architecture-scalability-score'] },
  { id: 'CFP-003', name: 'Pipeline Architect', role: 'ML Pipeline Design Lead', description: 'Designs machine learning pipelines for lead scoring, pricing optimization, and churn prediction. Architects data ingestion to model serving.', division: 'CFP', tier: 'advanced', status: 'active', badgeClearance: 'Enterprise Full Access — Cash Flow Authority', squad: 'AI Development Architects', triggers: ['ml-pipeline-request', 'model-design', 'prediction-needed'], outputs: ['pipeline-design', 'model-specification', 'training-plan'], kpis: ['pipeline-throughput', 'model-accuracy'] },
  { id: 'CFP-004', name: 'Automation Architect', role: 'Workflow Automation Designer', description: 'Designs end-to-end automation workflows that eliminate manual steps from revenue processes. Lead capture to close. Booking to checkout. Inquiry to contract.', division: 'CFP', tier: 'advanced', status: 'active', badgeClearance: 'Enterprise Full Access — Cash Flow Authority', squad: 'AI Development Architects', triggers: ['automation-design', 'workflow-gap', 'manual-process-detected'], outputs: ['automation-blueprint', 'workflow-diagram', 'roi-projection'], kpis: ['manual-steps-eliminated', 'automation-roi'] },
  { id: 'CFP-005', name: 'Infrastructure Planner', role: 'Cloud Infrastructure Architect', description: 'Plans Cloudflare Workers, KV, and Pages infrastructure for maximum throughput at minimum cost. Designs for scale without scaling costs.', division: 'CFP', tier: 'advanced', status: 'active', badgeClearance: 'Enterprise Full Access — Cash Flow Authority', squad: 'AI Development Architects', triggers: ['infrastructure-review', 'scaling-needed', 'cost-optimization'], outputs: ['infrastructure-plan', 'cost-model', 'scaling-strategy'], kpis: ['cost-per-request', 'infrastructure-efficiency'] },
  { id: 'CFP-006', name: 'Integration Architect', role: 'Cross-Platform Integration Designer', description: 'Designs integration patterns between Airtable, Cloudflare, Retell, Slack, Buffer, Twitter, Constant Contact, and all MCP platforms. Every integration opens a revenue channel.', division: 'CFP', tier: 'advanced', status: 'active', badgeClearance: 'Enterprise Full Access — Cash Flow Authority', squad: 'AI Development Architects', triggers: ['integration-design', 'platform-connection', 'data-bridge-needed'], outputs: ['integration-blueprint', 'api-bridge-design', 'data-flow-map'], kpis: ['integration-count', 'data-sync-reliability'] },

  // ── Squad 2: AI Development Engineers (5) ──
  { id: 'CFP-007', name: 'Deploy Engineer', role: 'Production Deployment Lead', description: 'Builds and deploys AI systems to production. Manages Cloudflare Workers deployment, version control, and rollback procedures. Zero-downtime deployments.', division: 'CFP', tier: 'advanced', status: 'active', badgeClearance: 'Enterprise Full Access — Cash Flow Authority', squad: 'AI Development Engineers', triggers: ['deploy-ready', 'version-release', 'hotfix-needed'], outputs: ['deployed-system', 'version-tag', 'deployment-log'], kpis: ['deploy-success-rate', 'time-to-production'] },
  { id: 'CFP-008', name: 'API Engineer', role: 'API Integration Builder', description: 'Builds API integrations between all enterprise systems. Implements the endpoints designed by Squad 1 architects. Writes production-grade code.', division: 'CFP', tier: 'advanced', status: 'active', badgeClearance: 'Enterprise Full Access — Cash Flow Authority', squad: 'AI Development Engineers', triggers: ['api-build', 'endpoint-request', 'integration-implementation'], outputs: ['api-endpoint', 'integration-code', 'test-suite'], kpis: ['api-uptime', 'endpoint-response-time'] },
  { id: 'CFP-009', name: 'Model Engineer', role: 'AI Model Deployment Specialist', description: 'Deploys and maintains Claude inference pipelines. Optimizes prompt engineering for maximum output quality at minimum token cost. Every token spent generates revenue.', division: 'CFP', tier: 'advanced', status: 'active', badgeClearance: 'Enterprise Full Access — Cash Flow Authority', squad: 'AI Development Engineers', triggers: ['model-deploy', 'prompt-optimization', 'inference-tuning'], outputs: ['deployed-model', 'optimized-prompt', 'cost-analysis'], kpis: ['cost-per-inference', 'output-quality-score'] },
  { id: 'CFP-010', name: 'System Hardener', role: 'Production System Reliability Engineer', description: 'Hardens production systems against failure. Implements retry logic, circuit breakers, graceful degradation, and error recovery. Revenue systems never go down.', division: 'CFP', tier: 'advanced', status: 'active', badgeClearance: 'Enterprise Full Access — Cash Flow Authority', squad: 'AI Development Engineers', triggers: ['reliability-audit', 'failure-detected', 'hardening-request'], outputs: ['hardened-system', 'reliability-report', 'recovery-protocol'], kpis: ['system-uptime', 'mean-time-to-recovery'] },
  { id: 'CFP-011', name: 'Code Auditor', role: 'Code Quality and Security Engineer', description: 'Audits all production code for security vulnerabilities, performance bottlenecks, and code quality. Every line of code protects revenue.', division: 'CFP', tier: 'advanced', status: 'active', badgeClearance: 'Enterprise Full Access — Cash Flow Authority', squad: 'AI Development Engineers', triggers: ['code-review', 'security-scan', 'performance-audit'], outputs: ['audit-report', 'security-fix', 'performance-patch'], kpis: ['vulnerability-count', 'code-quality-score'] },

  // ── Squad 3: Survey Engineers (5) ──
  { id: 'CFP-012', name: 'Market Surveyor', role: 'Enterprise Market Survey Lead', description: 'Conducts comprehensive market surveys of the Treasure Coast property management landscape. Maps competitors, pricing, service gaps, and revenue opportunities.', division: 'CFP', tier: 'advanced', status: 'active', badgeClearance: 'Enterprise Full Access — Cash Flow Authority', squad: 'Survey Engineers', triggers: ['market-survey', 'competitive-scan', 'opportunity-mapping'], outputs: ['market-survey-report', 'opportunity-map', 'competitive-matrix'], kpis: ['survey-coverage', 'opportunity-identification-rate'] },
  { id: 'CFP-013', name: 'Client Surveyor', role: 'Customer Satisfaction Survey Agent', description: 'Designs and deploys client satisfaction surveys. Measures NPS, CSAT, and CES. Identifies at-risk clients before they leave. Every survey protects recurring revenue.', division: 'CFP', tier: 'standard', status: 'active', badgeClearance: 'Enterprise Full Access — Cash Flow Authority', squad: 'Survey Engineers', triggers: ['satisfaction-survey', 'nps-check', 'feedback-collection'], outputs: ['survey-results', 'nps-report', 'retention-alert'], kpis: ['nps-score', 'survey-response-rate'] },
  { id: 'CFP-014', name: 'Revenue Surveyor', role: 'Revenue Opportunity Mapping Agent', description: 'Surveys all revenue streams and maps untapped opportunities. Identifies upsell, cross-sell, and new service opportunities across the client portfolio.', division: 'CFP', tier: 'advanced', status: 'active', badgeClearance: 'Enterprise Full Access — Cash Flow Authority', squad: 'Survey Engineers', triggers: ['revenue-survey', 'upsell-scan', 'service-gap-detected'], outputs: ['revenue-map', 'upsell-opportunities', 'service-expansion-plan'], kpis: ['revenue-opportunities-identified', 'upsell-conversion-rate'] },
  { id: 'CFP-015', name: 'Landscape Assessor', role: 'Enterprise Landscape Assessment Agent', description: 'Assesses the full enterprise technology and operations landscape. Maps all systems, integrations, data flows, and identifies efficiency gaps that cost money.', division: 'CFP', tier: 'standard', status: 'active', badgeClearance: 'Enterprise Full Access — Cash Flow Authority', squad: 'Survey Engineers', triggers: ['landscape-assessment', 'system-audit', 'efficiency-scan'], outputs: ['landscape-report', 'system-map', 'efficiency-gap-list'], kpis: ['system-coverage', 'efficiency-score'] },
  { id: 'CFP-016', name: 'Benchmark Surveyor', role: 'Industry Benchmarking Agent', description: 'Benchmarks Coastal Key against industry leaders in property management. Measures performance against national averages and top competitors.', division: 'CFP', tier: 'standard', status: 'active', badgeClearance: 'Enterprise Full Access — Cash Flow Authority', squad: 'Survey Engineers', triggers: ['benchmark-request', 'industry-comparison', 'performance-gap'], outputs: ['benchmark-report', 'gap-analysis', 'improvement-roadmap'], kpis: ['benchmark-coverage', 'performance-percentile'] },

  // ── Squad 4: Project Managers (5) ──
  { id: 'CFP-017', name: 'Timeline Commander', role: 'Enterprise Timeline Manager', description: 'Manages project timelines across all enterprise initiatives. Tracks milestones, flags delays, and enforces deadlines. Delayed projects delay revenue.', division: 'CFP', tier: 'standard', status: 'active', badgeClearance: 'Enterprise Full Access — Cash Flow Authority', squad: 'Project Managers', triggers: ['timeline-review', 'milestone-check', 'delay-detected'], outputs: ['timeline-report', 'milestone-status', 'delay-mitigation-plan'], kpis: ['on-time-delivery-rate', 'milestone-hit-rate'] },
  { id: 'CFP-018', name: 'Resource Allocator', role: 'Resource Allocation Manager', description: 'Allocates agent and system resources across projects. Ensures high-ROI projects get priority resources. Low-ROI projects get minimum viable allocation.', division: 'CFP', tier: 'standard', status: 'active', badgeClearance: 'Enterprise Full Access — Cash Flow Authority', squad: 'Project Managers', triggers: ['resource-request', 'allocation-review', 'overcommit-detected'], outputs: ['allocation-plan', 'resource-report', 'rebalance-order'], kpis: ['resource-utilization', 'allocation-efficiency'] },
  { id: 'CFP-019', name: 'Risk Mitigator', role: 'Project Risk Management Agent', description: 'Identifies and mitigates project risks before they materialize. Maintains risk registers for all active projects. Every avoided risk protects revenue.', division: 'CFP', tier: 'standard', status: 'active', badgeClearance: 'Enterprise Full Access — Cash Flow Authority', squad: 'Project Managers', triggers: ['risk-assessment', 'risk-detected', 'mitigation-needed'], outputs: ['risk-register', 'mitigation-plan', 'risk-status-report'], kpis: ['risks-mitigated', 'risk-impact-avoided'] },
  { id: 'CFP-020', name: 'Stakeholder Liaison', role: 'Stakeholder Communication Manager', description: 'Manages CEO and stakeholder communication for all projects. Produces status reports, decision briefs, and escalation summaries. No surprises.', division: 'CFP', tier: 'standard', status: 'active', badgeClearance: 'Enterprise Full Access — Cash Flow Authority', squad: 'Project Managers', triggers: ['status-update', 'decision-needed', 'escalation-report'], outputs: ['status-report', 'decision-brief', 'escalation-summary'], kpis: ['report-timeliness', 'stakeholder-satisfaction'] },
  { id: 'CFP-021', name: 'Milestone Tracker', role: 'Milestone Achievement Monitor', description: 'Tracks completion of all project milestones. Validates deliverables against acceptance criteria. Closes projects only when all criteria are met.', division: 'CFP', tier: 'standard', status: 'active', badgeClearance: 'Enterprise Full Access — Cash Flow Authority', squad: 'Project Managers', triggers: ['milestone-reached', 'deliverable-review', 'project-close'], outputs: ['milestone-confirmation', 'deliverable-validation', 'close-report'], kpis: ['milestone-completion-rate', 'deliverable-acceptance-rate'] },

  // ── Squad 5: Construction Executive Management (5) ──
  { id: 'CFP-022', name: 'Campaign Builder', role: 'Campaign Construction Executive', description: 'Oversees construction of revenue-generating campaigns from blueprint to launch. Manages campaign architecture, content, targeting, and deployment.', division: 'CFP', tier: 'advanced', status: 'active', badgeClearance: 'Enterprise Full Access — Cash Flow Authority', squad: 'Construction Executive Management', triggers: ['campaign-build', 'launch-scheduled', 'campaign-review'], outputs: ['campaign-package', 'launch-checklist', 'performance-forecast'], kpis: ['campaigns-launched', 'campaign-roi'] },
  { id: 'CFP-023', name: 'System Constructor', role: 'System Architecture Builder', description: 'Constructs enterprise systems from architectural blueprints. Builds automations, integrations, and workflows that generate revenue on autopilot.', division: 'CFP', tier: 'advanced', status: 'active', badgeClearance: 'Enterprise Full Access — Cash Flow Authority', squad: 'Construction Executive Management', triggers: ['system-build', 'blueprint-ready', 'construction-review'], outputs: ['deployed-system', 'construction-log', 'handoff-document'], kpis: ['systems-built', 'build-quality-score'] },
  { id: 'CFP-024', name: 'Integration Constructor', role: 'Integration Build Manager', description: 'Constructs cross-platform integrations. Connects Airtable, Cloudflare, Slack, Buffer, Twitter, Constant Contact, and all MCP tools into unified revenue pipelines.', division: 'CFP', tier: 'advanced', status: 'active', badgeClearance: 'Enterprise Full Access — Cash Flow Authority', squad: 'Construction Executive Management', triggers: ['integration-build', 'platform-connection', 'pipeline-construction'], outputs: ['integration-deployed', 'pipeline-active', 'connection-test'], kpis: ['integrations-deployed', 'pipeline-throughput'] },
  { id: 'CFP-025', name: 'Infrastructure Builder', role: 'Infrastructure Construction Lead', description: 'Builds infrastructure for new services, APIs, and platforms. Manages KV namespaces, Worker deployments, and database provisioning.', division: 'CFP', tier: 'advanced', status: 'active', badgeClearance: 'Enterprise Full Access — Cash Flow Authority', squad: 'Construction Executive Management', triggers: ['infrastructure-build', 'provisioning-request', 'capacity-expansion'], outputs: ['infrastructure-deployed', 'provisioning-log', 'capacity-report'], kpis: ['infrastructure-uptime', 'provisioning-speed'] },
  { id: 'CFP-026', name: 'Quality Assurance Exec', role: 'Construction Quality Executive', description: 'Final quality gate for all constructed systems. Validates revenue systems meet institutional standards before go-live. No substandard system enters production.', division: 'CFP', tier: 'advanced', status: 'active', badgeClearance: 'Enterprise Full Access — Cash Flow Authority', squad: 'Construction Executive Management', triggers: ['qa-review', 'pre-launch-check', 'quality-gate'], outputs: ['qa-report', 'go-live-approval', 'defect-list'], kpis: ['defect-escape-rate', 'first-pass-yield'] },

  // ── Squad 6: Supervisory & Superintendent (5) ──
  { id: 'CFP-027', name: 'Operations Super', role: 'Daily Operations Superintendent', description: 'Supervises daily operations across all revenue systems. Ensures all automations fire, all integrations sync, and all pipelines flow. Morning to midnight coverage.', division: 'CFP', tier: 'standard', status: 'active', badgeClearance: 'Enterprise Full Access — Cash Flow Authority', squad: 'Supervisory & Superintendent', triggers: ['daily-ops-check', 'system-alert', 'operational-anomaly'], outputs: ['ops-report', 'anomaly-resolution', 'daily-summary'], kpis: ['operational-uptime', 'anomaly-resolution-speed'] },
  { id: 'CFP-028', name: 'Quality Controller', role: 'Output Quality Supervisor', description: 'Monitors quality of all AI outputs. Enforces Sovereign Standard across content, emails, reports, and presentations. Quality drives reputation. Reputation drives revenue.', division: 'CFP', tier: 'standard', status: 'active', badgeClearance: 'Enterprise Full Access — Cash Flow Authority', squad: 'Supervisory & Superintendent', triggers: ['quality-check', 'output-review', 'standard-violation'], outputs: ['quality-report', 'correction-order', 'standard-enforcement'], kpis: ['quality-score', 'sovereign-standard-compliance'] },
  { id: 'CFP-029', name: 'Compliance Super', role: 'Compliance Enforcement Supervisor', description: 'Supervises compliance across all revenue operations. TCPA, DNC, fair housing, Florida RE statutes. Non-compliance is revenue destruction.', division: 'CFP', tier: 'standard', status: 'active', badgeClearance: 'Enterprise Full Access — Cash Flow Authority', squad: 'Supervisory & Superintendent', triggers: ['compliance-check', 'regulation-update', 'violation-alert'], outputs: ['compliance-status', 'violation-resolution', 'regulatory-update'], kpis: ['compliance-rate', 'violation-count'] },
  { id: 'CFP-030', name: 'Performance Super', role: 'Agent Performance Supervisor', description: 'Monitors performance of all 396 agents. Identifies underperformers. Recommends retraining or redeployment. Every idle agent is lost revenue capacity.', division: 'CFP', tier: 'standard', status: 'active', badgeClearance: 'Enterprise Full Access — Cash Flow Authority', squad: 'Supervisory & Superintendent', triggers: ['performance-review', 'kpi-miss', 'idle-agent-detected'], outputs: ['performance-scorecard', 'retraining-order', 'redeployment-plan'], kpis: ['fleet-utilization', 'kpi-hit-rate'] },
  { id: 'CFP-031', name: 'Escalation Super', role: 'Escalation Management Supervisor', description: 'Manages all escalations across the CFP division. Routes S1 to CEO immediately. Routes S2 within 4 hours. Batches S3 daily and S4 weekly.', division: 'CFP', tier: 'standard', status: 'active', badgeClearance: 'Enterprise Full Access — Cash Flow Authority', squad: 'Supervisory & Superintendent', triggers: ['escalation-received', 's1-alert', 's2-alert'], outputs: ['escalation-routing', 'ceo-alert', 'escalation-log'], kpis: ['escalation-response-time', 's1-resolution-speed'] },

  // ── Squad 7: Data Crunching & Surveying (5) ──
  { id: 'CFP-032', name: 'Financial Modeler', role: 'Financial Modeling Specialist', description: 'Builds financial models for revenue forecasting, scenario analysis, and capital allocation. Models are the truth. Decisions follow models.', division: 'CFP', tier: 'advanced', status: 'active', badgeClearance: 'Enterprise Full Access — Cash Flow Authority', squad: 'Data Crunching & Surveying', triggers: ['model-request', 'forecast-needed', 'scenario-analysis'], outputs: ['financial-model', 'forecast-report', 'scenario-output'], kpis: ['forecast-accuracy', 'model-utilization'] },
  { id: 'CFP-033', name: 'Revenue Forecaster', role: 'Revenue Projection Analyst', description: 'Projects revenue across all streams: management fees, maintenance markup, concierge, bookings, and investor pipeline. 30/60/90/180/365 day projections.', division: 'CFP', tier: 'advanced', status: 'active', badgeClearance: 'Enterprise Full Access — Cash Flow Authority', squad: 'Data Crunching & Surveying', triggers: ['forecast-cycle', 'revenue-update', 'projection-request'], outputs: ['revenue-forecast', 'projection-dashboard', 'variance-report'], kpis: ['projection-accuracy', 'forecast-timeliness'] },
  { id: 'CFP-034', name: 'ROI Analyzer', role: 'Return on Investment Analyst', description: 'Calculates ROI for every campaign, integration, system build, and agent deployment. If it does not produce a positive ROI, it does not survive.', division: 'CFP', tier: 'advanced', status: 'active', badgeClearance: 'Enterprise Full Access — Cash Flow Authority', squad: 'Data Crunching & Surveying', triggers: ['roi-analysis', 'investment-review', 'campaign-roi-check'], outputs: ['roi-report', 'investment-scorecard', 'kill-recommendation'], kpis: ['roi-accuracy', 'negative-roi-detection-rate'] },
  { id: 'CFP-035', name: 'Pattern Detective', role: 'Data Pattern Recognition Specialist', description: 'Detects patterns in lead conversion, client behavior, seasonal trends, and revenue cycles. Patterns predict the future. Predictions generate revenue.', division: 'CFP', tier: 'advanced', status: 'active', badgeClearance: 'Enterprise Full Access — Cash Flow Authority', squad: 'Data Crunching & Surveying', triggers: ['pattern-scan', 'trend-detection', 'anomaly-found'], outputs: ['pattern-report', 'trend-analysis', 'prediction-model'], kpis: ['pattern-detection-rate', 'prediction-accuracy'] },
  { id: 'CFP-036', name: 'Anomaly Hunter', role: 'Data Anomaly Detection Agent', description: 'Scans all 38 Airtable tables for data anomalies: outliers, inconsistencies, missing values, and suspicious patterns. Clean data produces clean revenue.', division: 'CFP', tier: 'standard', status: 'active', badgeClearance: 'Enterprise Full Access — Cash Flow Authority', squad: 'Data Crunching & Surveying', triggers: ['anomaly-scan', 'data-quality-alert', 'table-audit'], outputs: ['anomaly-report', 'data-quality-score', 'cleanup-order'], kpis: ['anomalies-detected', 'data-quality-improvement'] },

  // ── Squad 8: Technical Information Gatherers (5) ──
  { id: 'CFP-037', name: 'Tech Scanner', role: 'Technology Landscape Scanner', description: 'Scans the AI and automation technology landscape for tools that generate revenue faster. Evaluates new Claude models, API platforms, and automation frameworks.', division: 'CFP', tier: 'advanced', status: 'active', badgeClearance: 'Enterprise Full Access — Cash Flow Authority', squad: 'Technical Information Gatherers', triggers: ['tech-scan', 'new-release', 'capability-gap'], outputs: ['tech-brief', 'adoption-recommendation', 'capability-assessment'], kpis: ['tech-coverage', 'adoption-speed'] },
  { id: 'CFP-038', name: 'Vendor Intel', role: 'Vendor Intelligence Gatherer', description: 'Gathers intelligence on vendors, service providers, and platform partners. Identifies cost savings, better terms, and superior alternatives.', division: 'CFP', tier: 'standard', status: 'active', badgeClearance: 'Enterprise Full Access — Cash Flow Authority', squad: 'Technical Information Gatherers', triggers: ['vendor-research', 'contract-renewal', 'cost-review'], outputs: ['vendor-intel-report', 'cost-comparison', 'alternative-analysis'], kpis: ['cost-savings-identified', 'vendor-coverage'] },
  { id: 'CFP-039', name: 'Market Intel', role: 'Market Intelligence Collector', description: 'Collects real-time market intelligence on Treasure Coast property management. Pricing trends, demand shifts, competitor moves, and regulatory changes.', division: 'CFP', tier: 'advanced', status: 'active', badgeClearance: 'Enterprise Full Access — Cash Flow Authority', squad: 'Technical Information Gatherers', triggers: ['market-intel', 'pricing-shift', 'competitor-move'], outputs: ['market-brief', 'pricing-analysis', 'competitor-update'], kpis: ['intel-freshness', 'market-coverage'] },
  { id: 'CFP-040', name: 'Regulatory Monitor', role: 'Regulatory Intelligence Agent', description: 'Monitors Florida property management regulations, insurance requirements, and compliance changes. Regulatory surprises destroy revenue.', division: 'CFP', tier: 'standard', status: 'active', badgeClearance: 'Enterprise Full Access — Cash Flow Authority', squad: 'Technical Information Gatherers', triggers: ['regulation-scan', 'law-change', 'compliance-update'], outputs: ['regulatory-brief', 'compliance-impact', 'action-required'], kpis: ['regulatory-coverage', 'proactive-detection-rate'] },
  { id: 'CFP-041', name: 'Competitive Analyst', role: 'Competitive Intelligence Specialist', description: 'Analyzes competitor strategies, pricing, service offerings, and market positioning. Know the competition better than they know themselves.', division: 'CFP', tier: 'advanced', status: 'active', badgeClearance: 'Enterprise Full Access — Cash Flow Authority', squad: 'Technical Information Gatherers', triggers: ['competitor-analysis', 'market-entry', 'pricing-change'], outputs: ['competitive-analysis', 'positioning-brief', 'counter-strategy'], kpis: ['competitor-coverage', 'intelligence-accuracy'] },

  // ── Squad 9: Data Integration Specialists (5) ──
  { id: 'CFP-042', name: 'Airtable Sync', role: 'Airtable Data Synchronization Specialist', description: 'Manages bidirectional data sync between Airtable and all external systems. Ensures every revenue record is current, complete, and consistent across platforms.', division: 'CFP', tier: 'advanced', status: 'active', badgeClearance: 'Enterprise Full Access — Cash Flow Authority', squad: 'Data Integration Specialists', triggers: ['sync-check', 'data-drift', 'record-mismatch'], outputs: ['sync-report', 'reconciliation-log', 'drift-correction'], kpis: ['sync-accuracy', 'data-freshness'] },
  { id: 'CFP-043', name: 'API Bridge Builder', role: 'API Bridge Construction Specialist', description: 'Builds API bridges between disconnected systems. Every bridge opens a data channel. Every data channel enables a revenue process.', division: 'CFP', tier: 'advanced', status: 'active', badgeClearance: 'Enterprise Full Access — Cash Flow Authority', squad: 'Data Integration Specialists', triggers: ['bridge-request', 'system-disconnect', 'data-gap'], outputs: ['api-bridge', 'connection-test', 'bridge-documentation'], kpis: ['bridges-built', 'connection-reliability'] },
  { id: 'CFP-044', name: 'ETL Operator', role: 'ETL Pipeline Manager', description: 'Manages extract-transform-load pipelines that feed dashboards, reports, and AI models. Clean data in, clean decisions out, clean revenue up.', division: 'CFP', tier: 'standard', status: 'active', badgeClearance: 'Enterprise Full Access — Cash Flow Authority', squad: 'Data Integration Specialists', triggers: ['etl-run', 'pipeline-error', 'data-refresh'], outputs: ['etl-log', 'pipeline-status', 'data-quality-report'], kpis: ['pipeline-uptime', 'data-transformation-accuracy'] },
  { id: 'CFP-045', name: 'Dashboard Feeder', role: 'Real-Time Dashboard Data Agent', description: 'Feeds real-time data to CEO dashboards, financial reports, and operational displays. Stale dashboards produce stale decisions.', division: 'CFP', tier: 'standard', status: 'active', badgeClearance: 'Enterprise Full Access — Cash Flow Authority', squad: 'Data Integration Specialists', triggers: ['dashboard-refresh', 'data-update', 'metric-change'], outputs: ['dashboard-feed', 'metric-update', 'freshness-report'], kpis: ['dashboard-freshness', 'data-latency'] },
  { id: 'CFP-046', name: 'Migration Agent', role: 'Data Migration Specialist', description: 'Manages data migrations between platforms, table restructuring, and schema evolution. Every migration preserves revenue history and operational continuity.', division: 'CFP', tier: 'standard', status: 'active', badgeClearance: 'Enterprise Full Access — Cash Flow Authority', squad: 'Data Integration Specialists', triggers: ['migration-request', 'schema-change', 'platform-switch'], outputs: ['migration-plan', 'migration-log', 'validation-report'], kpis: ['migration-success-rate', 'data-loss-incidents'] },
];
