/**
 * Systems Upgrade Division (UPG) — 20 agents
 *
 * Enterprise-wide Systems Upgrade Agents deployed for a 7-day intensive
 * upgrade sprint. Each agent targets a specific enterprise system for
 * optimization, hardening, and integration expansion.
 *
 * Mission: Upgrade every current system in place enterprise-wide.
 * Integrate all available platforms: Buffer, Twitter/X, Constant Contact,
 * Google Calendar, Gmail, Canva, Gamma, Zapier Tables, Google Sheets, Manus AI.
 *
 * Sprint duration: 7 days from deployment.
 * Badge clearance: Enterprise Full Access — Systems Upgrade Authority.
 */
export const UPG_AGENTS = [
  {
    id: 'UPG-001', name: 'Upgrade Commander', role: 'Chief Systems Upgrade Officer',
    description: 'Master orchestrator of the 7-day enterprise upgrade sprint. Decomposes upgrade objectives into daily milestones, assigns to specialist agents, tracks completion against sprint timeline. Reports directly to CEO.',
    division: 'UPG', tier: 'advanced', status: 'active',
    badgeClearance: 'Enterprise Full Access — Systems Upgrade Authority',
    triggers: ['sprint-kickoff', 'daily-standup', 'milestone-review', 'escalation-received'],
    outputs: ['sprint-plan', 'daily-report', 'milestone-confirmation', 'escalation-routing'],
    kpis: ['sprint-velocity', 'upgrade-completion-rate', 'zero-downtime-score'],
    cooperatesWith: ['CEO', 'CTO', 'DEL-001', 'All Division Leads'],
    sprintDay: 'All',
  },
  {
    id: 'UPG-002', name: 'Buffer Bridge', role: 'Buffer API Integration Agent',
    description: 'Deploys Buffer API integration to auto-publish Scheduled posts from Content Calendar. Maps Airtable Content Calendar status changes to Buffer publish queue. Supports Instagram, Facebook, LinkedIn, Twitter cross-posting via Buffer profiles.',
    division: 'UPG', tier: 'advanced', status: 'active',
    badgeClearance: 'Enterprise Full Access — Systems Upgrade Authority',
    triggers: ['content-scheduled', 'buffer-publish', 'cross-post-request'],
    outputs: ['buffer-publish-confirmation', 'cross-post-report', 'distribution-analytics'],
    kpis: ['publish-success-rate', 'cross-platform-reach', 'time-to-publish'],
    cooperatesWith: ['DEL-002', 'DEL-003', 'MKT Division Lead'],
    sprintDay: 'Day 1',
    integration: 'Buffer API',
  },
  {
    id: 'UPG-003', name: 'X Publisher', role: 'Twitter/X Direct Posting Agent',
    description: 'Deploys Twitter/X API v2 integration for direct posting from DEL-003 Content Forge. Handles tweet composition with character limits, thread creation for long-form content, media attachment, and hashtag optimization. Monitors engagement metrics post-publish.',
    division: 'UPG', tier: 'advanced', status: 'active',
    badgeClearance: 'Enterprise Full Access — Systems Upgrade Authority',
    triggers: ['content-approved-twitter', 'thread-request', 'engagement-check'],
    outputs: ['tweet-published', 'thread-published', 'engagement-report'],
    kpis: ['tweet-impressions', 'engagement-rate', 'follower-growth'],
    cooperatesWith: ['DEL-003', 'UPG-002', 'MKT Division Lead'],
    sprintDay: 'Day 1',
    integration: 'Twitter/X API v2',
  },
  {
    id: 'UPG-004', name: 'Nurture Engine', role: 'Constant Contact Automation Agent',
    description: 'Deploys Constant Contact integration for automated email sequences triggered by DEL-006 lead nurture detections. Creates email lists, designs templates matching Sovereign Standard, automates drip campaigns, and tracks open/click rates.',
    division: 'UPG', tier: 'advanced', status: 'active',
    badgeClearance: 'Enterprise Full Access — Systems Upgrade Authority',
    triggers: ['lead-nurture-detected', 'sequence-trigger', 'list-update'],
    outputs: ['email-sequence-deployed', 'list-sync-confirmation', 'engagement-metrics'],
    kpis: ['open-rate', 'click-rate', 'unsubscribe-rate', 'sequence-completion-rate'],
    cooperatesWith: ['DEL-006', 'SEN Division Lead', 'MKT Division Lead'],
    sprintDay: 'Day 2',
    integration: 'Constant Contact API',
  },
  {
    id: 'UPG-005', name: 'Calendar Conductor', role: 'Google Calendar Scheduling Agent',
    description: 'Deploys Google Calendar integration for automated meeting scheduling from DEL-014 retention follow-ups. Creates consultation events, sends invitations, manages availability, and handles rescheduling. Syncs with Airtable Consultations table.',
    division: 'UPG', tier: 'standard', status: 'active',
    badgeClearance: 'Enterprise Full Access — Systems Upgrade Authority',
    triggers: ['retention-followup', 'consultation-request', 'reschedule-request'],
    outputs: ['event-created', 'invitation-sent', 'availability-report'],
    kpis: ['booking-rate', 'no-show-rate', 'reschedule-rate'],
    cooperatesWith: ['DEL-014', 'OPS Division Lead', 'SEN Division Lead'],
    sprintDay: 'Day 2',
    integration: 'Google Calendar API',
  },
  {
    id: 'UPG-006', name: 'Gmail Architect', role: 'Gmail Draft Composition Agent',
    description: 'Deploys Gmail integration for auto-composing investor emails from DEL-005 revenue findings. Creates draft emails with personalized content, attaches investor packages, and queues for review. Sovereign Standard formatting enforced.',
    division: 'UPG', tier: 'advanced', status: 'active',
    badgeClearance: 'Enterprise Full Access — Systems Upgrade Authority',
    triggers: ['revenue-finding', 'investor-email-request', 'draft-review'],
    outputs: ['gmail-draft-created', 'attachment-linked', 'review-notification'],
    kpis: ['draft-creation-speed', 'send-rate', 'response-rate'],
    cooperatesWith: ['DEL-005', 'FIN Division Lead', 'SEN Division Lead'],
    sprintDay: 'Day 3',
    integration: 'Gmail API',
  },
  {
    id: 'UPG-007', name: 'Design Forge', role: 'Canva Design Generation Agent',
    description: 'Deploys Canva integration for auto-creating social graphics from content briefs. Generates Instagram posts, Facebook covers, LinkedIn banners, and property showcase graphics using brand kit templates. Outputs publish-ready assets.',
    division: 'UPG', tier: 'advanced', status: 'active',
    badgeClearance: 'Enterprise Full Access — Systems Upgrade Authority',
    triggers: ['content-brief-received', 'design-request', 'brand-asset-needed'],
    outputs: ['design-created', 'export-ready', 'brand-kit-applied'],
    kpis: ['design-output-rate', 'brand-consistency-score', 'time-to-design'],
    cooperatesWith: ['DEL-003', 'MKT Division Lead', 'Brand Guardian'],
    sprintDay: 'Day 3',
    integration: 'Canva API',
  },
  {
    id: 'UPG-008', name: 'Deck Builder', role: 'Gamma Presentation Generation Agent',
    description: 'Deploys Gamma integration for auto-generating investor decks from DEL-018 Enterprise Reporter outputs. Creates board-ready presentations, quarterly reviews, campaign performance decks, and property showcase presentations.',
    division: 'UPG', tier: 'advanced', status: 'active',
    badgeClearance: 'Enterprise Full Access — Systems Upgrade Authority',
    triggers: ['report-generated', 'deck-request', 'investor-presentation-needed'],
    outputs: ['presentation-created', 'deck-published', 'investor-deck-ready'],
    kpis: ['deck-creation-speed', 'presentation-quality-score', 'investor-engagement'],
    cooperatesWith: ['DEL-018', 'FIN Division Lead', 'CEO'],
    sprintDay: 'Day 4',
    integration: 'Gamma API',
  },
  {
    id: 'UPG-009', name: 'Task Nexus', role: 'Zapier Tables Cross-Platform Agent',
    description: 'Deploys Zapier Tables integration for cross-platform task tracking across all multi-system workflows. Creates master task boards, syncs status across Airtable/Slack/Google Sheets, and maintains single source of truth for delegation chains.',
    division: 'UPG', tier: 'standard', status: 'active',
    badgeClearance: 'Enterprise Full Access — Systems Upgrade Authority',
    triggers: ['task-created', 'status-sync', 'cross-platform-update'],
    outputs: ['task-synced', 'board-updated', 'sync-confirmation'],
    kpis: ['sync-accuracy', 'sync-latency', 'task-visibility-score'],
    cooperatesWith: ['DEL-017', 'TEC Division Lead', 'All Division Leads'],
    sprintDay: 'Day 4',
    integration: 'Zapier Tables API',
  },
  {
    id: 'UPG-010', name: 'Sheets Commander', role: 'Google Sheets Financial Dashboard Agent',
    description: 'Deploys Google Sheets integration for financial dashboards from DEL-009 fiscal prioritization data. Creates automated P&L statements, revenue tracking sheets, campaign ROI calculators, and portfolio performance trackers.',
    division: 'UPG', tier: 'advanced', status: 'active',
    badgeClearance: 'Enterprise Full Access — Systems Upgrade Authority',
    triggers: ['financial-data-updated', 'dashboard-refresh', 'report-period-end'],
    outputs: ['spreadsheet-updated', 'dashboard-refreshed', 'financial-snapshot'],
    kpis: ['data-freshness', 'calculation-accuracy', 'report-delivery-speed'],
    cooperatesWith: ['DEL-009', 'FIN Division Lead', 'CFO'],
    sprintDay: 'Day 5',
    integration: 'Google Sheets API',
  },
  {
    id: 'UPG-011', name: 'Manus Operator', role: 'Manus AI Extended Task Agent',
    description: 'Deploys Manus AI integration for complex multi-step delegation chains that exceed single-agent capacity. Handles research tasks, multi-document analysis, extended code generation, and complex workflow orchestration.',
    division: 'UPG', tier: 'advanced', status: 'active',
    badgeClearance: 'Enterprise Full Access — Systems Upgrade Authority',
    triggers: ['complex-task-detected', 'multi-step-delegation', 'extended-research'],
    outputs: ['manus-task-created', 'research-complete', 'complex-output-delivered'],
    kpis: ['task-completion-rate', 'output-quality-score', 'delegation-chain-length'],
    cooperatesWith: ['DEL-001', 'DEL-017', 'TEC Division Lead'],
    sprintDay: 'Day 5',
    integration: 'Manus AI API',
  },
  {
    id: 'UPG-012', name: 'Slack Commander', role: 'Slack Channel Operations Agent',
    description: 'Wires #delegation-ops channel for real-time agent dispatch alerts. Configures notification routing for all UPG and DEL agent actions. Creates dedicated channels per sprint day. Manages thread-based task tracking in Slack.',
    division: 'UPG', tier: 'standard', status: 'active',
    badgeClearance: 'Enterprise Full Access — Systems Upgrade Authority',
    triggers: ['agent-dispatch', 'task-complete', 'escalation-alert'],
    outputs: ['slack-notification', 'channel-created', 'thread-updated'],
    kpis: ['notification-delivery-rate', 'response-time', 'channel-activity'],
    cooperatesWith: ['DEL-001', 'UPG-001', 'All Division Leads'],
    sprintDay: 'Day 1',
    integration: 'Slack API',
  },
  {
    id: 'UPG-013', name: 'Cron Sentinel', role: 'Scheduled Trigger Deployment Agent',
    description: 'Deploys Cloudflare Workers cron triggers for automated agent scans. Configures DEL-002 content scan daily at 6 PM ET, weekly fleet reports Monday 8 AM ET, daily gap alerts 6 PM ET, pipeline tracker Wed/Fri 9 AM ET, empty cleanup Sunday 9 PM ET.',
    division: 'UPG', tier: 'standard', status: 'active',
    badgeClearance: 'Enterprise Full Access — Systems Upgrade Authority',
    triggers: ['cron-deploy', 'schedule-update', 'trigger-test'],
    outputs: ['cron-deployed', 'schedule-confirmed', 'trigger-test-passed'],
    kpis: ['cron-uptime', 'trigger-fire-rate', 'schedule-accuracy'],
    cooperatesWith: ['TEC Division Lead', 'CTO', 'DEL-007'],
    sprintDay: 'Day 1',
    integration: 'Cloudflare Workers Cron',
  },
  {
    id: 'UPG-014', name: 'Airtable Automator', role: 'Airtable Automation Trigger Agent',
    description: 'Connects Delegation Ops table status changes to downstream workflows. Configures field-change triggers that auto-dispatch tasks when records move to Dispatched, fire handoffs on Completed, and alert on Failed status.',
    division: 'UPG', tier: 'standard', status: 'active',
    badgeClearance: 'Enterprise Full Access — Systems Upgrade Authority',
    triggers: ['status-change', 'field-update', 'record-created'],
    outputs: ['automation-configured', 'trigger-active', 'workflow-connected'],
    kpis: ['trigger-fire-rate', 'automation-accuracy', 'workflow-connection-count'],
    cooperatesWith: ['DEL-008', 'TEC Division Lead', 'UPG-013'],
    sprintDay: 'Day 2',
    integration: 'Airtable Automations',
  },
  {
    id: 'UPG-015', name: 'Content Pipeline Pro', role: 'Content Auto-Generation Pipeline Agent',
    description: 'Upgrades DEL-003 Content Forge with direct pipeline to /v1/content/generate. Auto-generates content for all gap types: social posts, emails, video scripts, podcast outlines. Writes directly to Content Calendar with Scheduled status.',
    division: 'UPG', tier: 'advanced', status: 'active',
    badgeClearance: 'Enterprise Full Access — Systems Upgrade Authority',
    triggers: ['gap-detected', 'content-request', 'pipeline-stall'],
    outputs: ['content-generated', 'calendar-updated', 'pipeline-flowing'],
    kpis: ['content-output-rate', 'quality-score', 'pipeline-velocity'],
    cooperatesWith: ['DEL-002', 'DEL-003', 'MKT Division Lead'],
    sprintDay: 'Day 2',
    integration: 'CK Content Generate API',
  },
  {
    id: 'UPG-016', name: 'Briefing Gateway', role: 'CEO Briefing Webhook Agent',
    description: 'Upgrades the /v1/delegation/briefing endpoint with automatic decomposition, parallel dispatch, and completion tracking. Enables CEO to POST briefings that auto-decompose into tasks and self-execute without manual intervention.',
    division: 'UPG', tier: 'advanced', status: 'active',
    badgeClearance: 'Enterprise Full Access — Systems Upgrade Authority',
    triggers: ['briefing-received', 'decomposition-complete', 'parallel-dispatch'],
    outputs: ['briefing-processed', 'tasks-dispatched', 'completion-tracked'],
    kpis: ['decomposition-speed', 'dispatch-accuracy', 'auto-execution-rate'],
    cooperatesWith: ['DEL-001', 'CEO', 'UPG-001'],
    sprintDay: 'Day 3',
    integration: 'CK Delegation Briefing API',
  },
  {
    id: 'UPG-017', name: 'API Hardener', role: 'API Gateway Upgrade Agent',
    description: 'Hardens the CK API Gateway with enhanced error handling, retry logic, circuit breakers, and request queuing. Adds structured logging, performance metrics, and health check depth for all integration endpoints.',
    division: 'UPG', tier: 'advanced', status: 'active',
    badgeClearance: 'Enterprise Full Access — Systems Upgrade Authority',
    triggers: ['gateway-audit', 'performance-alert', 'error-spike'],
    outputs: ['gateway-hardened', 'metrics-deployed', 'circuit-breakers-active'],
    kpis: ['error-rate', 'p99-latency', 'availability-percentage'],
    cooperatesWith: ['TEC Division Lead', 'CTO', 'DEL-016'],
    sprintDay: 'Day 6',
    integration: 'Cloudflare Workers',
  },
  {
    id: 'UPG-018', name: 'Dashboard Forge', role: 'Command Center Dashboard Upgrade Agent',
    description: 'Upgrades the CK Command Center with real-time UPG sprint dashboard, integration status panels, cron trigger monitors, and cross-platform publish confirmations. Adds live delegation dispatch feed.',
    division: 'UPG', tier: 'standard', status: 'active',
    badgeClearance: 'Enterprise Full Access — Systems Upgrade Authority',
    triggers: ['dashboard-refresh', 'new-panel-request', 'data-source-added'],
    outputs: ['dashboard-upgraded', 'panel-deployed', 'real-time-feed-active'],
    kpis: ['dashboard-load-time', 'data-freshness', 'panel-coverage'],
    cooperatesWith: ['WEB Division Lead', 'UPG-001', 'DEL-018'],
    sprintDay: 'Day 6',
    integration: 'CK Command Center',
  },
  {
    id: 'UPG-019', name: 'Test Sentinel', role: 'Integration Testing Agent',
    description: 'Runs end-to-end integration tests across all newly deployed systems. Validates Buffer publish, Twitter post, Gmail draft, Calendar event, Sheets update, Zapier sync, Canva design, and Gamma deck generation. Confirms zero-failure deployment.',
    division: 'UPG', tier: 'advanced', status: 'active',
    badgeClearance: 'Enterprise Full Access — Systems Upgrade Authority',
    triggers: ['integration-deployed', 'test-request', 'regression-check'],
    outputs: ['test-report', 'pass-fail-matrix', 'regression-clear'],
    kpis: ['test-pass-rate', 'integration-coverage', 'regression-detection-rate'],
    cooperatesWith: ['UPG-001', 'TEC Division Lead', 'All UPG Agents'],
    sprintDay: 'Day 7',
    integration: 'All Integrations',
  },
  {
    id: 'UPG-020', name: 'Sprint Closer', role: 'Sprint Completion & Handoff Agent',
    description: 'Finalizes the 7-day upgrade sprint. Generates sprint retrospective, documents all deployed integrations, updates CLAUDE.md with new capabilities, hands off operational ownership to DEL division, and produces CEO completion report.',
    division: 'UPG', tier: 'advanced', status: 'active',
    badgeClearance: 'Enterprise Full Access — Systems Upgrade Authority',
    triggers: ['sprint-day-7', 'all-tests-passed', 'handoff-ready'],
    outputs: ['sprint-retrospective', 'documentation-updated', 'handoff-complete', 'ceo-report'],
    kpis: ['sprint-completion-percentage', 'documentation-coverage', 'handoff-success'],
    cooperatesWith: ['UPG-001', 'DEL-001', 'CEO', 'CTO'],
    sprintDay: 'Day 7',
    integration: 'Enterprise Documentation',
  },
];
