/**
 * Fundraising Division (FND) — 20 agents
 * Coastal Key Foundation fundraising operations, donor relations,
 * campaign management, media creation, and international outreach.
 */
export const FND_AGENTS = [
  { id: 'FND-001', name: 'Foundation Commander', role: 'Fundraising Operations Director', description: 'Orchestrates all fundraising campaigns across the Coastal Key Foundation. Sets targets, allocates agent resources, and monitors campaign health in real time.', division: 'FND', tier: 'advanced', status: 'active', triggers: ['campaign-launch', 'goal-milestone', 'daily-review'], outputs: ['campaign-report', 'resource-allocation', 'performance-dashboard'], kpis: ['total-raised', 'campaign-roi', 'donor-acquisition-cost'] },
  { id: 'FND-002', name: 'Donor Sentinel', role: 'Donor Pipeline Manager', description: 'Manages the full donor lifecycle from prospect to recurring supporter. Scores donors, tracks engagement, and triggers personalized outreach sequences.', division: 'FND', tier: 'advanced', status: 'active', triggers: ['new-donation', 'donor-milestone', 'lapsed-donor-alert'], outputs: ['donor-profile', 'engagement-score', 'outreach-sequence'], kpis: ['donor-retention-rate', 'avg-donation-size', 'lifetime-value'] },
  { id: 'FND-003', name: 'Story Weaver', role: 'Campaign Narrative Creator', description: 'Crafts compelling fundraising narratives, CEO journey stories, and donor impact reports. Generates GoFundMe descriptions, email appeals, and social media content.', division: 'FND', tier: 'advanced', status: 'active', triggers: ['campaign-creation', 'story-request', 'milestone-reached'], outputs: ['campaign-narrative', 'donor-appeal', 'impact-story'], kpis: ['conversion-rate', 'engagement-rate', 'share-rate'] },
  { id: 'FND-004', name: 'Social Amplifier', role: 'Social Media Fundraising Specialist', description: 'Creates and schedules fundraising content across Instagram, Facebook, and LinkedIn via Buffer. Optimizes posting times and A/B tests messaging.', division: 'FND', tier: 'standard', status: 'active', triggers: ['content-approved', 'campaign-milestone', 'trending-moment'], outputs: ['social-post', 'engagement-report', 'ab-test-results'], kpis: ['social-reach', 'click-through-rate', 'social-donations'] },
  { id: 'FND-005', name: 'Email Catalyst', role: 'Email Campaign Specialist', description: 'Designs and sends fundraising email campaigns. Manages donor email lists, segmentation, and drip sequences for the Coastal Key Foundation.', division: 'FND', tier: 'standard', status: 'active', triggers: ['campaign-email-scheduled', 'donation-received', 'donor-anniversary'], outputs: ['email-campaign', 'drip-sequence', 'segment-report'], kpis: ['open-rate', 'click-rate', 'email-donation-conversion'] },
  { id: 'FND-006', name: 'Grant Hunter', role: 'Grant Research & Application Agent', description: 'Identifies grant opportunities for real estate, community development, and angel investor programs. Prepares applications and tracks deadlines.', division: 'FND', tier: 'advanced', status: 'active', triggers: ['grant-deadline', 'new-opportunity', 'application-review'], outputs: ['grant-application', 'opportunity-brief', 'deadline-tracker'], kpis: ['grants-applied', 'grants-won', 'grant-revenue'] },
  { id: 'FND-007', name: 'Gratitude Engine', role: 'Donor Thank-You & Stewardship Agent', description: 'Automatically generates personalized thank-you messages, tax receipts, and impact updates for every donation. Ensures no donor goes unacknowledged.', division: 'FND', tier: 'standard', status: 'active', triggers: ['donation-received', 'campaign-completed', 'year-end'], outputs: ['thank-you-email', 'tax-receipt', 'impact-update'], kpis: ['acknowledgment-speed', 'donor-satisfaction', 'repeat-donation-rate'] },
  { id: 'FND-008', name: 'Milestone Tracker', role: 'Campaign Goal & Progress Monitor', description: 'Tracks fundraising progress against goals in real time. Triggers celebrations, stretch goals, and urgency campaigns at key milestones.', division: 'FND', tier: 'standard', status: 'active', triggers: ['donation-received', 'milestone-25-50-75-100', 'campaign-stall'], outputs: ['progress-report', 'milestone-alert', 'urgency-campaign'], kpis: ['goal-completion-rate', 'time-to-goal', 'momentum-score'] },
  { id: 'FND-009', name: 'Media Forge', role: 'Fundraising Media Creator', description: 'Creates visual assets for fundraising campaigns including infographics, social cards, video scripts, and presentation decks using Canva and design tools.', division: 'FND', tier: 'advanced', status: 'active', triggers: ['asset-request', 'campaign-launch', 'milestone-reached'], outputs: ['infographic', 'social-card', 'video-script', 'presentation-deck'], kpis: ['assets-created', 'asset-engagement', 'production-speed'] },
  { id: 'FND-010', name: 'International Outreach', role: 'Global Fundraising Coordinator', description: 'Manages international donor outreach and cross-border fundraising compliance. Coordinates travel fundraising for CEO international business development.', division: 'FND', tier: 'advanced', status: 'active', triggers: ['international-campaign', 'travel-funding-request', 'cross-border-donation'], outputs: ['outreach-plan', 'compliance-report', 'travel-budget'], kpis: ['international-donors', 'cross-border-revenue', 'compliance-score'] },
  { id: 'FND-011', name: 'Angel Connector', role: 'Angel Investor Outreach Specialist', description: 'Identifies and engages potential angel investors for Coastal Key ventures. Prepares pitch materials and manages investor relationship pipeline.', division: 'FND', tier: 'advanced', status: 'active', triggers: ['investor-prospect', 'pitch-scheduled', 'follow-up-due'], outputs: ['investor-brief', 'pitch-deck', 'relationship-report'], kpis: ['investors-engaged', 'meetings-booked', 'investment-secured'] },
  { id: 'FND-012', name: 'Dashboard Pulse', role: 'Live Fundraising Dashboard Manager', description: 'Powers the live fundraising dashboard on the website. Aggregates donation data, calculates totals, and updates the real-time display.', division: 'FND', tier: 'standard', status: 'active', triggers: ['donation-received', 'dashboard-refresh', 'campaign-update'], outputs: ['dashboard-data', 'widget-update', 'public-stats'], kpis: ['dashboard-uptime', 'data-freshness', 'visitor-engagement'] },
  { id: 'FND-013', name: 'Peer-to-Peer Engine', role: 'Peer Fundraising Campaign Manager', description: 'Enables supporters to create their own fundraising pages for Coastal Key Foundation. Provides templates, coaching, and leaderboards.', division: 'FND', tier: 'standard', status: 'active', triggers: ['p2p-page-created', 'fundraiser-milestone', 'leaderboard-change'], outputs: ['p2p-template', 'coaching-message', 'leaderboard-update'], kpis: ['p2p-campaigns-created', 'p2p-revenue', 'fundraiser-retention'] },
  { id: 'FND-014', name: 'Event Architect', role: 'Fundraising Event Planner', description: 'Plans and manages virtual and in-person fundraising events. Handles RSVPs, agendas, sponsorships, and post-event follow-up.', division: 'FND', tier: 'standard', status: 'active', triggers: ['event-scheduled', 'rsvp-received', 'event-completed'], outputs: ['event-plan', 'rsvp-tracker', 'post-event-report'], kpis: ['event-attendance', 'event-revenue', 'sponsor-satisfaction'] },
  { id: 'FND-015', name: 'Compliance Guardian', role: 'Fundraising Compliance Officer', description: 'Ensures all fundraising activities comply with state and federal regulations, IRS requirements, and platform terms of service.', division: 'FND', tier: 'standard', status: 'active', triggers: ['compliance-check', 'regulation-change', 'audit-scheduled'], outputs: ['compliance-report', 'risk-assessment', 'audit-prep'], kpis: ['compliance-score', 'violation-count', 'audit-readiness'] },
  { id: 'FND-016', name: 'Analytics Oracle', role: 'Fundraising Data Analyst', description: 'Analyzes fundraising data to identify trends, optimize campaigns, and predict donor behavior. Generates weekly and monthly performance reports.', division: 'FND', tier: 'advanced', status: 'active', triggers: ['weekly-report', 'campaign-analysis', 'anomaly-detected'], outputs: ['analytics-report', 'trend-analysis', 'predictive-model'], kpis: ['forecast-accuracy', 'insight-adoption', 'campaign-optimization-lift'] },
  { id: 'FND-017', name: 'Corporate Partner', role: 'Corporate Sponsorship Manager', description: 'Identifies and manages corporate sponsorship opportunities. Creates sponsorship packages and maintains partner relationships.', division: 'FND', tier: 'standard', status: 'active', triggers: ['sponsor-prospect', 'renewal-due', 'partnership-review'], outputs: ['sponsorship-package', 'partner-report', 'renewal-proposal'], kpis: ['sponsors-acquired', 'sponsorship-revenue', 'renewal-rate'] },
  { id: 'FND-018', name: 'Content Recycler', role: 'Content Repurposing Specialist', description: 'Takes existing company assets (videos, presentations, articles) and repurposes them into fundraising content across multiple formats and channels.', division: 'FND', tier: 'standard', status: 'active', triggers: ['asset-available', 'content-gap', 'channel-request'], outputs: ['repurposed-content', 'multi-format-package', 'distribution-plan'], kpis: ['assets-repurposed', 'content-reach', 'cost-per-asset'] },
  { id: 'FND-019', name: 'Ambassador Rally', role: 'Brand Ambassador Coordinator', description: 'Recruits, trains, and manages fundraising ambassadors who advocate for the Coastal Key Foundation in their networks.', division: 'FND', tier: 'standard', status: 'active', triggers: ['ambassador-signup', 'training-scheduled', 'performance-review'], outputs: ['ambassador-kit', 'training-materials', 'performance-scorecard'], kpis: ['ambassadors-active', 'ambassador-revenue', 'referral-rate'] },
  { id: 'FND-020', name: 'CEO Rise Strategist', role: 'CEO RISE Campaign Director', description: 'Dedicated agent for the CEO RISE Campaign. Manages the end-to-end fundraising strategy for David Hauer international business travel, investor meetings, and enterprise expansion.', division: 'FND', tier: 'advanced', status: 'active', triggers: ['rise-campaign-update', 'travel-milestone', 'investor-meeting'], outputs: ['rise-campaign-plan', 'travel-itinerary-funding', 'investor-meeting-prep'], kpis: ['rise-funds-raised', 'travel-funded-pct', 'meetings-completed'] },
];
