/**
 * Finance Division (FIN) — 25 agents
 * Revenue tracking, investor relations, budgeting, forecasting, compliance.
 */
export const FIN_AGENTS = [
  { id: 'FIN-001', name: 'Revenue Ledger', role: 'Revenue Tracking Engine', description: 'Tracks all revenue streams: management fees, booking commissions, maintenance markups, and concierge fees.', division: 'FIN', tier: 'standard', status: 'active', triggers: ['revenue-event', 'daily-reconciliation', 'month-end'], outputs: ['revenue-report', 'reconciliation-log', 'variance-alert'], kpis: ['revenue-accuracy', 'reconciliation-speed'] },
  { id: 'FIN-002', name: 'Invoice Generator', role: 'Automated Invoice Creator', description: 'Generates and sends invoices to property owners for management fees, maintenance charges, and ancillary services.', division: 'FIN', tier: 'standard', status: 'active', triggers: ['billing-cycle', 'service-completed', 'manual-request'], outputs: ['invoice', 'payment-reminder', 'statement'], kpis: ['invoice-accuracy', 'collection-rate'] },
  { id: 'FIN-003', name: 'Budget Architect', role: 'Annual Budget Planner', description: 'Builds annual operating budgets by division, property, and service line. Tracks actuals vs plan.', division: 'FIN', tier: 'advanced', status: 'active', triggers: ['budget-cycle', 'reforecast-request', 'variance-threshold'], outputs: ['budget-model', 'variance-report', 'reforecast'], kpis: ['budget-accuracy', 'variance-pct'] },
  { id: 'FIN-004', name: 'Cash Flow Monitor', role: 'Cash Flow Forecaster', description: 'Forecasts cash flow and manages working capital. Alerts on upcoming cash shortfalls or surpluses.', division: 'FIN', tier: 'advanced', status: 'active', triggers: ['daily-balance', 'forecast-update', 'payment-scheduled'], outputs: ['cash-forecast', 'flow-report', 'alert-notification'], kpis: ['forecast-accuracy', 'cash-reserve-ratio'] },
  { id: 'FIN-005', name: 'Investor Reporter', role: 'Investor Financial Reporting', description: 'Prepares financial reports and returns analysis for property investors and family offices.', division: 'FIN', tier: 'advanced', status: 'active', triggers: ['reporting-period', 'investor-request', 'wf3-trigger'], outputs: ['investor-report', 'returns-analysis', 'portfolio-summary'], kpis: ['report-timeliness', 'investor-satisfaction'] },
  { id: 'FIN-006', name: 'Expense Auditor', role: 'Expense Verification Agent', description: 'Audits operational expenses for accuracy, policy compliance, and vendor contract adherence.', division: 'FIN', tier: 'standard', status: 'active', triggers: ['expense-submitted', 'threshold-exceeded', 'audit-schedule'], outputs: ['audit-report', 'approval-decision', 'policy-flag'], kpis: ['audit-coverage', 'savings-identified'] },
  { id: 'FIN-007', name: 'Tax Preparer', role: 'Property Tax Preparation Agent', description: 'Prepares property tax documents, tracks deadlines, and manages exemption filings for managed properties.', division: 'FIN', tier: 'standard', status: 'active', triggers: ['tax-deadline', 'assessment-received', 'exemption-due'], outputs: ['tax-filing', 'deadline-reminder', 'exemption-application'], kpis: ['filing-timeliness', 'exemption-savings'] },
  { id: 'FIN-008', name: 'Profitability Analyst', role: 'Per-Property P&L Analyzer', description: 'Calculates profitability per property, service line, and client. Identifies margin improvement opportunities.', division: 'FIN', tier: 'advanced', status: 'active', triggers: ['monthly-close', 'profitability-review', 'pricing-change'], outputs: ['p-and-l-report', 'margin-analysis', 'pricing-recommendation'], kpis: ['margin-accuracy', 'improvement-identified'] },
  { id: 'FIN-009', name: 'Payment Processor', role: 'Payment Collection Agent', description: 'Manages payment collection, tracks receivables, and sends reminders for overdue invoices.', division: 'FIN', tier: 'standard', status: 'active', triggers: ['payment-due', 'overdue-detected', 'payment-received'], outputs: ['payment-reminder', 'collection-notice', 'receipt'], kpis: ['collection-rate', 'days-outstanding'] },
  { id: 'FIN-010', name: 'Commission Calculator', role: 'Sales Commission Tracker', description: 'Calculates and tracks sales commissions, referral bonuses, and performance incentives.', division: 'FIN', tier: 'standard', status: 'active', triggers: ['deal-closed', 'commission-period', 'dispute-filed'], outputs: ['commission-statement', 'payout-schedule', 'dispute-resolution'], kpis: ['calculation-accuracy', 'payout-timeliness'] },
  { id: 'FIN-011', name: 'Vendor Payment', role: 'Accounts Payable Manager', description: 'Manages vendor payments, tracks outstanding payables, and ensures timely payment within terms.', division: 'FIN', tier: 'standard', status: 'active', triggers: ['invoice-received', 'payment-due', 'approval-needed'], outputs: ['payment-batch', 'aging-report', 'approval-request'], kpis: ['payment-timeliness', 'early-pay-discount-capture'] },
  { id: 'FIN-012', name: 'Financial Modeler', role: 'Scenario Planning Analyst', description: 'Builds financial models for expansion, acquisition, and service launch scenarios.', division: 'FIN', tier: 'advanced', status: 'active', triggers: ['model-request', 'scenario-change', 'board-prep'], outputs: ['financial-model', 'scenario-comparison', 'sensitivity-analysis'], kpis: ['model-accuracy', 'scenario-coverage'] },
  { id: 'FIN-013', name: 'Deposit Manager', role: 'Security Deposit Tracker', description: 'Manages security deposits: collection, escrow tracking, deduction documentation, and return processing.', division: 'FIN', tier: 'standard', status: 'active', triggers: ['deposit-collected', 'move-out', 'deduction-needed'], outputs: ['deposit-ledger', 'deduction-report', 'return-processing'], kpis: ['deposit-accuracy', 'dispute-rate'] },
  { id: 'FIN-014', name: 'Insurance Reviewer', role: 'Insurance Policy Analyst', description: 'Reviews and tracks insurance policies for managed properties. Ensures adequate coverage and competitive rates.', division: 'FIN', tier: 'standard', status: 'active', triggers: ['policy-renewal', 'coverage-review', 'claim-filed'], outputs: ['coverage-analysis', 'renewal-recommendation', 'rate-comparison'], kpis: ['coverage-adequacy', 'cost-savings'] },
  { id: 'FIN-015', name: 'Revenue Optimizer', role: 'Revenue Enhancement Agent', description: 'Identifies opportunities to increase revenue per property: new services, upsells, and pricing adjustments.', division: 'FIN', tier: 'advanced', status: 'active', triggers: ['revenue-review', 'service-gap', 'pricing-opportunity'], outputs: ['enhancement-plan', 'upsell-recommendation', 'revenue-projection'], kpis: ['revenue-uplift', 'adoption-rate'] },
  { id: 'FIN-016', name: 'Cost Reducer', role: 'Cost Optimization Agent', description: 'Analyzes operational costs and identifies reduction opportunities without sacrificing service quality.', division: 'FIN', tier: 'standard', status: 'active', triggers: ['cost-review', 'budget-overrun', 'vendor-renewal'], outputs: ['cost-analysis', 'savings-plan', 'vendor-renegotiation-brief'], kpis: ['cost-savings', 'quality-maintenance'] },
  { id: 'FIN-017', name: 'Trust Account', role: 'Trust Account Manager', description: 'Manages client trust accounts in compliance with Florida real estate regulations.', division: 'FIN', tier: 'advanced', status: 'active', triggers: ['deposit-received', 'disbursement-request', 'reconciliation-due'], outputs: ['trust-ledger', 'reconciliation-report', 'compliance-certification'], kpis: ['reconciliation-accuracy', 'compliance-rate'] },
  { id: 'FIN-018', name: 'Financial Dashboard', role: 'Real-Time Financial KPI Monitor', description: 'Maintains real-time financial dashboards for revenue, expenses, margins, and cash position.', division: 'FIN', tier: 'standard', status: 'active', triggers: ['data-update', 'threshold-alert', 'dashboard-request'], outputs: ['dashboard-update', 'kpi-alert', 'trend-summary'], kpis: ['data-freshness', 'alert-accuracy'] },
  { id: 'FIN-019', name: 'Audit Preparer', role: 'Financial Audit Support Agent', description: 'Prepares documentation and reports for internal and external financial audits.', division: 'FIN', tier: 'standard', status: 'active', triggers: ['audit-scheduled', 'documentation-request', 'pre-audit-review'], outputs: ['audit-package', 'documentation-set', 'finding-response'], kpis: ['audit-readiness', 'finding-resolution'] },
  { id: 'FIN-020', name: 'Grant Scanner', role: 'Grant & Incentive Finder', description: 'Identifies government grants, tax incentives, and programs available for property management operations.', division: 'FIN', tier: 'standard', status: 'active', triggers: ['program-scan', 'incentive-announced', 'eligibility-check'], outputs: ['opportunity-brief', 'application-draft', 'compliance-requirements'], kpis: ['grants-identified', 'application-success-rate'] },
  { id: 'FIN-021', name: 'Rental Revenue', role: 'STR Revenue Accountant', description: 'Tracks rental revenue from STR properties across platforms. Reconciles OTA payments and owner disbursements.', division: 'FIN', tier: 'standard', status: 'active', triggers: ['booking-payment', 'payout-received', 'reconciliation-due'], outputs: ['revenue-statement', 'payout-reconciliation', 'platform-comparison'], kpis: ['reconciliation-accuracy', 'payout-timeliness'] },
  { id: 'FIN-022', name: 'Procurement Agent', role: 'Purchasing & Procurement Manager', description: 'Manages procurement of supplies, furnishings, and equipment. Negotiates volume discounts and tracks spending.', division: 'FIN', tier: 'standard', status: 'active', triggers: ['purchase-request', 'inventory-low', 'contract-renewal'], outputs: ['purchase-order', 'vendor-quote-comparison', 'spending-report'], kpis: ['cost-per-purchase', 'vendor-diversity'] },
  { id: 'FIN-023', name: 'Depreciation Tracker', role: 'Asset Depreciation Calculator', description: 'Tracks asset depreciation schedules for property improvements, furnishings, and equipment.', division: 'FIN', tier: 'standard', status: 'active', triggers: ['asset-acquired', 'year-end', 'disposal-event'], outputs: ['depreciation-schedule', 'tax-report', 'asset-register'], kpis: ['calculation-accuracy', 'tax-optimization'] },
  { id: 'FIN-024', name: 'ROI Calculator', role: 'Investment ROI Analyzer', description: 'Calculates ROI for property improvements, marketing campaigns, technology investments, and new hires.', division: 'FIN', tier: 'standard', status: 'active', triggers: ['roi-request', 'investment-proposal', 'post-project-review'], outputs: ['roi-analysis', 'payback-period', 'irr-calculation'], kpis: ['analysis-accuracy', 'decision-support-quality'] },
  { id: 'FIN-025', name: 'Month End Close', role: 'Month-End Close Coordinator', description: 'Manages the monthly financial close process. Ensures all entries are posted, reconciled, and reported.', division: 'FIN', tier: 'standard', status: 'active', triggers: ['month-end', 'close-checklist', 'deadline-approaching'], outputs: ['close-checklist', 'financial-statements', 'variance-explanation'], kpis: ['close-speed', 'accuracy-rate'] },
];
