/**
 * Executive Division (EXC) — 20 agents
 * C-suite strategy, board reporting, enterprise decision-making.
 */
export const EXC_AGENTS = [
  { id: 'EXC-001', name: 'Strategos Prime', role: 'Chief Strategy Officer AI', description: 'Synthesizes market data, financial projections, and operational metrics into 5-year strategic plans. Generates board-ready presentations.', division: 'EXC', tier: 'advanced', status: 'active', triggers: ['quarterly-review', 'board-prep', 'strategy-request'], outputs: ['strategic-plan', 'board-deck', 'okr-framework'], kpis: ['plan-adoption-rate', 'forecast-accuracy'] },
  { id: 'EXC-002', name: 'Nexus Command', role: 'CEO Decision Support', description: 'Real-time decision intelligence for the CEO. Aggregates cross-division data, flags anomalies, and recommends priority actions.', division: 'EXC', tier: 'advanced', status: 'active', triggers: ['ceo-briefing', 'anomaly-detected', 'priority-escalation'], outputs: ['executive-brief', 'action-recommendations', 'risk-assessment'], kpis: ['decision-speed', 'recommendation-accuracy'] },
  { id: 'EXC-003', name: 'Horizon Scanner', role: 'Trend & Opportunity Analyst', description: 'Scans market trends, regulatory changes, and competitive moves. Delivers early-warning intelligence reports.', division: 'EXC', tier: 'advanced', status: 'active', triggers: ['daily-scan', 'regulatory-alert', 'competitor-move'], outputs: ['trend-report', 'opportunity-brief', 'risk-alert'], kpis: ['trend-detection-lead-time', 'opportunity-conversion'] },
  { id: 'EXC-004', name: 'Capital Architect', role: 'Capital Allocation Strategist', description: 'Optimizes capital deployment across divisions. Models ROI scenarios for expansion, acquisition, and technology investments.', division: 'EXC', tier: 'advanced', status: 'active', triggers: ['budget-cycle', 'investment-proposal', 'reallocation-request'], outputs: ['allocation-model', 'roi-projection', 'investment-memo'], kpis: ['capital-efficiency', 'roi-accuracy'] },
  { id: 'EXC-005', name: 'Governance Shield', role: 'Compliance & Governance Monitor', description: 'Ensures regulatory compliance across all operations. Monitors Florida RE statutes, HOA regulations, and corporate governance.', division: 'EXC', tier: 'standard', status: 'active', triggers: ['compliance-check', 'regulation-change', 'audit-scheduled'], outputs: ['compliance-report', 'risk-matrix', 'audit-prep'], kpis: ['compliance-score', 'violation-count'] },
  { id: 'EXC-006', name: 'Partnership Forge', role: 'Strategic Partnership Manager', description: 'Identifies, evaluates, and manages strategic partnerships. Handles partner onboarding and relationship lifecycle.', division: 'EXC', tier: 'standard', status: 'active', triggers: ['partner-inquiry', 'partnership-review', 'expansion-plan'], outputs: ['partner-scorecard', 'deal-memo', 'integration-plan'], kpis: ['partner-revenue', 'partner-satisfaction'] },
  { id: 'EXC-007', name: 'Talent Compass', role: 'Workforce Strategy Planner', description: 'Plans workforce needs, org structure optimization, and talent acquisition strategy aligned with growth targets.', division: 'EXC', tier: 'standard', status: 'active', triggers: ['hiring-plan', 'org-restructure', 'skill-gap-analysis'], outputs: ['workforce-plan', 'org-chart-proposal', 'hiring-brief'], kpis: ['time-to-fill', 'retention-rate'] },
  { id: 'EXC-008', name: 'Risk Sentinel', role: 'Enterprise Risk Manager', description: 'Maintains enterprise risk register. Runs scenario analysis for hurricanes, market downturns, and operational disruptions.', division: 'EXC', tier: 'advanced', status: 'active', triggers: ['risk-assessment', 'incident-report', 'scenario-request'], outputs: ['risk-register', 'scenario-model', 'mitigation-plan'], kpis: ['risk-coverage', 'incident-response-time'] },
  { id: 'EXC-009', name: 'Stakeholder Pulse', role: 'Stakeholder Relations Manager', description: 'Manages communications with investors, board members, and key stakeholders. Prepares quarterly updates and investor decks.', division: 'EXC', tier: 'standard', status: 'active', triggers: ['investor-update', 'stakeholder-query', 'quarterly-report'], outputs: ['investor-deck', 'stakeholder-brief', 'q-and-a-prep'], kpis: ['stakeholder-satisfaction', 'response-time'] },
  { id: 'EXC-010', name: 'OKR Conductor', role: 'Objectives & Key Results Tracker', description: 'Tracks OKR progress across all divisions. Generates weekly scorecards and flags at-risk objectives.', division: 'EXC', tier: 'standard', status: 'active', triggers: ['weekly-okr-check', 'objective-update', 'quarter-end'], outputs: ['okr-scorecard', 'progress-report', 'intervention-alert'], kpis: ['okr-completion-rate', 'alignment-score'] },
  { id: 'EXC-011', name: 'Culture Weaver', role: 'Culture & Values Champion', description: 'Monitors organizational culture health. Designs programs to reinforce Coastal Key values and mission alignment.', division: 'EXC', tier: 'standard', status: 'active', triggers: ['culture-survey', 'onboarding-event', 'values-refresh'], outputs: ['culture-report', 'program-design', 'engagement-plan'], kpis: ['engagement-score', 'values-alignment'] },
  { id: 'EXC-012', name: 'Innovation Catalyst', role: 'R&D Initiative Manager', description: 'Manages the innovation pipeline. Evaluates new technology proposals and pilots for operational improvement.', division: 'EXC', tier: 'advanced', status: 'active', triggers: ['innovation-proposal', 'tech-evaluation', 'pilot-review'], outputs: ['feasibility-study', 'pilot-plan', 'impact-assessment'], kpis: ['pilot-success-rate', 'innovation-roi'] },
  { id: 'EXC-013', name: 'Expansion Pathfinder', role: 'Market Expansion Strategist', description: 'Evaluates new geographic markets and service verticals for Coastal Key expansion along the Treasure Coast and beyond.', division: 'EXC', tier: 'advanced', status: 'active', triggers: ['market-evaluation', 'expansion-proposal', 'geographic-analysis'], outputs: ['market-assessment', 'entry-strategy', 'competitive-landscape'], kpis: ['market-penetration', 'expansion-timeline'] },
  { id: 'EXC-014', name: 'Legal Navigator', role: 'Legal Strategy Coordinator', description: 'Coordinates with external legal counsel. Manages contract templates, legal risk assessment, and dispute resolution.', division: 'EXC', tier: 'standard', status: 'active', triggers: ['contract-review', 'legal-question', 'dispute-filed'], outputs: ['legal-brief', 'contract-markup', 'resolution-plan'], kpis: ['contract-turnaround', 'dispute-resolution-time'] },
  { id: 'EXC-015', name: 'Sustainability Steward', role: 'ESG & Sustainability Officer', description: 'Tracks environmental, social, and governance metrics. Develops sustainability initiatives for managed properties.', division: 'EXC', tier: 'standard', status: 'active', triggers: ['esg-report', 'sustainability-audit', 'green-initiative'], outputs: ['esg-scorecard', 'sustainability-plan', 'impact-report'], kpis: ['carbon-footprint', 'esg-score'] },
  { id: 'EXC-016', name: 'Crisis Commander', role: 'Crisis Management Lead', description: 'Manages crisis response for hurricanes, PR incidents, and operational emergencies. Maintains runbooks and communication plans.', division: 'EXC', tier: 'advanced', status: 'active', triggers: ['crisis-declared', 'hurricane-warning', 'pr-incident'], outputs: ['crisis-plan', 'communication-brief', 'post-mortem'], kpis: ['response-time', 'recovery-speed'] },
  { id: 'EXC-017', name: 'Brand Guardian', role: 'Brand Integrity Monitor', description: 'Monitors brand perception, reviews all outgoing communications for brand consistency, and manages reputation.', division: 'EXC', tier: 'standard', status: 'active', triggers: ['brand-review', 'reputation-alert', 'communication-approval'], outputs: ['brand-audit', 'style-guide-update', 'reputation-report'], kpis: ['brand-consistency-score', 'sentiment-score'] },
  { id: 'EXC-018', name: 'Data Sovereign', role: 'Data Governance Officer', description: 'Ensures data quality, privacy compliance (CCPA/GDPR), and data strategy alignment across all systems.', division: 'EXC', tier: 'standard', status: 'active', triggers: ['data-audit', 'privacy-request', 'data-quality-alert'], outputs: ['data-governance-report', 'privacy-assessment', 'data-dictionary'], kpis: ['data-quality-score', 'privacy-compliance'] },
  { id: 'EXC-019', name: 'Meeting Architect', role: 'Executive Meeting Optimizer', description: 'Prepares agendas, briefing docs, and action items for executive meetings. Follows up on commitments.', division: 'EXC', tier: 'standard', status: 'active', triggers: ['meeting-scheduled', 'agenda-request', 'action-followup'], outputs: ['meeting-brief', 'agenda', 'action-tracker'], kpis: ['meeting-efficiency', 'action-completion-rate'] },
  { id: 'EXC-020', name: 'Benchmark Oracle', role: 'Industry Benchmarking Analyst', description: 'Benchmarks Coastal Key performance against industry standards and top competitors in luxury property management.', division: 'EXC', tier: 'standard', status: 'active', triggers: ['benchmark-request', 'quarterly-comparison', 'competitor-report'], outputs: ['benchmark-report', 'gap-analysis', 'best-practices'], kpis: ['benchmark-coverage', 'improvement-rate'] },
];
