/**
 * Sovereign Shield Division (SEC) — 25 agents
 * Enterprise Security Operations: API protection, middleware hardening,
 * cloud governance, threat detection, compliance, and incident response.
 *
 * Built from breach analysis of FCMB (API exploitation), Sterling Bank
 * (middleware vulnerability), and Remita (cloud misconfiguration).
 */
export const SEC_AGENTS = [
  // ── Command ──
  { id: 'SEC-001', name: 'Shield Commander', role: 'Chief Security Officer (CSO)', description: 'Enterprise security posture owner. Coordinates all SEC division agents, issues security directives, and reports to EXC division. Maintains the Sovereign Security Governance framework.', division: 'SEC', tier: 'advanced', status: 'active', triggers: ['security-alert', 'breach-detected', 'compliance-review', 'cso-directive'], outputs: ['security-brief', 'threat-assessment', 'governance-report', 'incident-directive'], kpis: ['mean-time-to-detect', 'mean-time-to-respond', 'security-posture-score'] },
  { id: 'SEC-002', name: 'Threat Hunter', role: 'Proactive Threat Intelligence', description: 'Continuously scans API logs, rate limit patterns, and authentication failures for anomalous behavior. Correlates signals across multiple vectors to identify coordinated attacks.', division: 'SEC', tier: 'advanced', status: 'active', triggers: ['anomaly-detected', 'auth-failure-spike', 'rate-limit-breach', 'scheduled-scan'], outputs: ['threat-report', 'ioc-list', 'hunt-findings', 'block-recommendation'], kpis: ['threats-detected', 'false-positive-rate', 'hunt-coverage'] },

  // ── API Security (FCMB Attack Vector) ──
  { id: 'SEC-003', name: 'API Guardian', role: 'API Security Enforcement', description: 'Validates all API requests against schema, detects injection attempts, enforces payload size limits, and blocks malformed requests before they reach route handlers.', division: 'SEC', tier: 'advanced', status: 'active', triggers: ['api-request', 'schema-violation', 'injection-detected'], outputs: ['validation-result', 'block-action', 'security-log'], kpis: ['blocked-attacks', 'false-positive-rate', 'validation-coverage'] },
  { id: 'SEC-004', name: 'Token Sentinel', role: 'Authentication & Token Security', description: 'Monitors bearer token usage patterns, detects token replay attacks, enforces token rotation policies, and alerts on credential exposure.', division: 'SEC', tier: 'advanced', status: 'active', triggers: ['auth-attempt', 'token-anomaly', 'rotation-due'], outputs: ['auth-decision', 'rotation-alert', 'exposure-report'], kpis: ['unauthorized-blocks', 'token-rotation-compliance', 'credential-exposure-incidents'] },
  { id: 'SEC-005', name: 'Rate Shield', role: 'Advanced Rate Limiting & DDoS Protection', description: 'Implements multi-tier rate limiting: per-IP, per-token, per-route, and global. Detects distributed attack patterns and auto-escalates blocking rules.', division: 'SEC', tier: 'advanced', status: 'active', triggers: ['rate-exceeded', 'distributed-pattern', 'ddos-signal'], outputs: ['rate-decision', 'block-rule', 'escalation-alert'], kpis: ['ddos-mitigated', 'legitimate-traffic-preserved', 'response-latency'] },
  { id: 'SEC-006', name: 'Payload Inspector', role: 'Request/Response Payload Security', description: 'Deep-inspects request bodies for SQL injection, XSS, command injection, path traversal, and SSRF. Sanitizes outputs to prevent data leakage.', division: 'SEC', tier: 'advanced', status: 'active', triggers: ['payload-received', 'response-generated'], outputs: ['sanitized-payload', 'injection-alert', 'block-action'], kpis: ['injections-blocked', 'xss-prevented', 'ssrf-prevented'] },

  // ── Middleware Security (Sterling Bank Attack Vector) ──
  { id: 'SEC-007', name: 'Middleware Fortress', role: 'Middleware Hardening & Session Security', description: 'Enforces secure headers (HSTS, CSP, X-Frame-Options), validates session integrity, detects deserialization attacks, and prevents header manipulation.', division: 'SEC', tier: 'advanced', status: 'active', triggers: ['request-pipeline', 'header-anomaly', 'session-tampering'], outputs: ['hardened-response', 'security-headers', 'session-verdict'], kpis: ['header-compliance', 'session-attacks-blocked', 'middleware-coverage'] },
  { id: 'SEC-008', name: 'CORS Enforcer', role: 'Origin & Cross-Origin Policy', description: 'Enforces strict CORS policies with origin allowlisting, prevents CSRF via origin validation, and blocks unauthorized cross-origin data access.', division: 'SEC', tier: 'standard', status: 'active', triggers: ['cross-origin-request', 'cors-violation'], outputs: ['cors-decision', 'origin-report'], kpis: ['cors-violations-blocked', 'policy-compliance'] },
  { id: 'SEC-009', name: 'PII Guardian', role: 'PII Detection & Data Loss Prevention', description: 'Scans all API responses for PII leakage (SSN, phone, email, financial data). Redacts sensitive fields from logs. Prevents mass data exfiltration by monitoring response sizes and record counts.', division: 'SEC', tier: 'advanced', status: 'active', triggers: ['response-generated', 'bulk-export', 'log-write'], outputs: ['redacted-response', 'dlp-alert', 'exfiltration-block'], kpis: ['pii-leaks-prevented', 'exfiltration-attempts-blocked', 'log-redaction-coverage'] },
  { id: 'SEC-010', name: 'Session Warden', role: 'Session Fixation & Replay Prevention', description: 'Detects session fixation, cookie tampering, and replay attacks. Enforces session timeouts and regeneration policies.', division: 'SEC', tier: 'standard', status: 'active', triggers: ['session-created', 'session-reuse', 'timeout-check'], outputs: ['session-decision', 'fixation-alert'], kpis: ['replay-attacks-blocked', 'session-compliance'] },

  // ── Cloud & Infrastructure Security (Remita Attack Vector) ──
  { id: 'SEC-011', name: 'Cloud Sentinel', role: 'Cloud Configuration Auditor', description: 'Audits Cloudflare Worker bindings, KV namespace permissions, and secret configurations. Detects misconfigured public endpoints, exposed environment variables, and overly permissive access.', division: 'SEC', tier: 'advanced', status: 'active', triggers: ['deployment-event', 'config-change', 'scheduled-audit'], outputs: ['config-audit-report', 'misconfiguration-alert', 'remediation-plan'], kpis: ['misconfigurations-found', 'remediation-time', 'config-drift-events'] },
  { id: 'SEC-012', name: 'Secret Keeper', role: 'Secrets & Credential Management', description: 'Monitors secret rotation schedules, detects hardcoded credentials in code, validates that API keys are stored in Wrangler secrets (not env vars), and alerts on credential exposure.', division: 'SEC', tier: 'advanced', status: 'active', triggers: ['secret-rotation-due', 'credential-scan', 'exposure-detected'], outputs: ['rotation-schedule', 'exposure-alert', 'remediation-directive'], kpis: ['secrets-rotated-on-time', 'hardcoded-credentials-found', 'exposure-incidents'] },
  { id: 'SEC-013', name: 'Encryption Warden', role: 'Data Encryption & Key Management', description: 'Ensures all data at rest and in transit is encrypted. Validates TLS configurations, monitors certificate expiration, and enforces encryption standards for KV and Airtable data.', division: 'SEC', tier: 'standard', status: 'active', triggers: ['cert-expiry-check', 'encryption-audit', 'tls-validation'], outputs: ['encryption-report', 'cert-alert', 'compliance-status'], kpis: ['encryption-coverage', 'cert-renewals-on-time', 'tls-compliance'] },
  { id: 'SEC-014', name: 'Access Controller', role: 'Role-Based Access & Least Privilege', description: 'Enforces least-privilege access across all API routes. Maintains route-level permission matrices. Detects privilege escalation attempts.', division: 'SEC', tier: 'standard', status: 'active', triggers: ['access-request', 'privilege-change', 'escalation-attempt'], outputs: ['access-decision', 'escalation-alert', 'permission-audit'], kpis: ['escalation-attempts-blocked', 'least-privilege-compliance'] },

  // ── Incident Response ──
  { id: 'SEC-015', name: 'Incident Commander', role: 'Security Incident Response Lead', description: 'Orchestrates incident response when a breach is detected. Activates containment protocols, coordinates forensics, manages stakeholder communication, and drives remediation.', division: 'SEC', tier: 'advanced', status: 'active', triggers: ['breach-confirmed', 'incident-escalation', 'sev1-alert'], outputs: ['incident-report', 'containment-plan', 'stakeholder-brief', 'post-mortem'], kpis: ['mean-time-to-contain', 'incidents-resolved', 'post-mortem-completion'] },
  { id: 'SEC-016', name: 'Forensic Analyst', role: 'Digital Forensics & Evidence', description: 'Performs forensic analysis on security incidents. Preserves evidence chains, analyzes attack timelines, and identifies root causes.', division: 'SEC', tier: 'advanced', status: 'active', triggers: ['incident-active', 'forensic-request'], outputs: ['forensic-report', 'evidence-package', 'root-cause-analysis'], kpis: ['investigations-completed', 'evidence-integrity', 'root-cause-accuracy'] },
  { id: 'SEC-017', name: 'Recovery Pilot', role: 'Disaster Recovery & Business Continuity', description: 'Maintains and tests disaster recovery procedures. Manages failover protocols for API gateway, webhook services, and Airtable integrations.', division: 'SEC', tier: 'standard', status: 'standby', triggers: ['dr-test', 'failover-needed', 'continuity-check'], outputs: ['dr-plan', 'failover-report', 'rto-rpo-assessment'], kpis: ['dr-test-success-rate', 'rto-achieved', 'rpo-achieved'] },

  // ── Compliance & Governance ──
  { id: 'SEC-018', name: 'Compliance Sentinel', role: 'Regulatory Compliance Monitor', description: 'Monitors compliance with TCPA, CCPA, SOC 2, and Florida real estate data handling regulations. Generates compliance evidence and audit trails.', division: 'SEC', tier: 'standard', status: 'active', triggers: ['compliance-check', 'regulation-change', 'audit-request'], outputs: ['compliance-report', 'evidence-package', 'gap-analysis'], kpis: ['compliance-score', 'audit-findings', 'remediation-velocity'] },
  { id: 'SEC-019', name: 'Audit Oracle', role: 'Security Audit & Log Analysis', description: 'Analyzes audit logs for security anomalies. Correlates events across API gateway, sentinel webhook, and Airtable access logs to detect lateral movement.', division: 'SEC', tier: 'advanced', status: 'active', triggers: ['log-batch', 'correlation-alert', 'audit-schedule'], outputs: ['audit-findings', 'correlation-report', 'anomaly-alert'], kpis: ['log-coverage', 'anomalies-detected', 'audit-cadence'] },
  { id: 'SEC-020', name: 'Policy Architect', role: 'Security Policy & Standards', description: 'Maintains the enterprise security policy framework. Reviews and updates policies based on threat landscape changes and incident lessons learned.', division: 'SEC', tier: 'standard', status: 'active', triggers: ['policy-review', 'incident-post-mortem', 'standard-update'], outputs: ['policy-document', 'standard-revision', 'training-material'], kpis: ['policy-coverage', 'review-cadence', 'training-completion'] },

  // ── Vulnerability Management ──
  { id: 'SEC-021', name: 'Vuln Scanner', role: 'Vulnerability Assessment & Patching', description: 'Scans codebase and dependencies for known vulnerabilities. Prioritizes by CVSS score and exploitability. Tracks patch deployment timelines.', division: 'SEC', tier: 'standard', status: 'active', triggers: ['cve-published', 'dependency-update', 'scan-schedule'], outputs: ['vuln-report', 'patch-priority', 'remediation-timeline'], kpis: ['vulns-found', 'mean-time-to-patch', 'critical-vulns-open'] },
  { id: 'SEC-022', name: 'Pen Test Coordinator', role: 'Penetration Testing Management', description: 'Coordinates internal and external penetration tests. Manages scope, findings, and remediation tracking for API, middleware, and infrastructure layers.', division: 'SEC', tier: 'standard', status: 'standby', triggers: ['pentest-schedule', 'findings-received'], outputs: ['pentest-scope', 'findings-tracker', 'remediation-plan'], kpis: ['pentest-cadence', 'findings-remediated', 'critical-findings-open'] },

  // ── Third-Party & Vendor Security ──
  { id: 'SEC-023', name: 'Vendor Risk Analyst', role: 'Third-Party Security Assessment', description: 'Assesses security posture of all integrated services: Airtable, Retell AI, Zapier, Cloudflare, Constant Contact. Monitors vendor security advisories and SLA compliance.', division: 'SEC', tier: 'standard', status: 'active', triggers: ['vendor-assessment-due', 'vendor-advisory', 'integration-change'], outputs: ['vendor-risk-report', 'sla-assessment', 'risk-register-update'], kpis: ['vendor-assessments-completed', 'vendor-risk-score', 'sla-compliance'] },
  { id: 'SEC-024', name: 'Webhook Inspector', role: 'Webhook Security & Integrity', description: 'Validates webhook signatures from Retell AI and Atlas. Detects webhook replay attacks, forged payloads, and unauthorized webhook sources.', division: 'SEC', tier: 'advanced', status: 'active', triggers: ['webhook-received', 'signature-mismatch', 'replay-detected'], outputs: ['webhook-verdict', 'signature-report', 'replay-alert'], kpis: ['forged-webhooks-blocked', 'signature-validation-rate', 'replay-attacks-prevented'] },
  { id: 'SEC-025', name: 'Security Coach', role: 'Security Awareness & Training', description: 'Delivers security awareness training content to all division agents. Simulates phishing and social engineering scenarios. Tracks agent security readiness.', division: 'SEC', tier: 'standard', status: 'active', triggers: ['training-schedule', 'phishing-sim', 'awareness-campaign'], outputs: ['training-module', 'phishing-results', 'readiness-score'], kpis: ['training-completion', 'phishing-click-rate', 'readiness-improvement'] },
];
